"use client";

import { useState } from "react";
import type { DirectorRun } from "@/lib/director-ai";

const starter = "NASA discovers a hidden ocean beneath an icy moon";
function Score({ label, value }: { label: string; value: number }) { return <div><div className="flex justify-between text-xs"><span className="text-slate-400">{label}</span><span className="font-mono text-cyan-100">{value}</span></div><div className="mt-2 h-1.5 rounded-full bg-white/8"><div className="h-full rounded-full bg-gradient-to-r from-cyan-300 to-violet-400" style={{ width: `${value}%` }} /></div></div>; }

export function DirectorDashboard() {
  const [discovery, setDiscovery] = useState(starter);
  const [run, setRun] = useState<DirectorRun | null>(null);
  const [tab, setTab] = useState<"pipeline" | "variants" | "reviews" | "decisions">("pipeline");
  const [busy, setBusy] = useState(false);
  async function runDirector() { setBusy(true); try { const response = await fetch("/api/director", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ discovery }) }); const payload = (await response.json()) as { director?: DirectorRun }; if (payload.director) setRun(payload.director); } finally { setBusy(false); } }
  function download(name: string, content: string) { const url = URL.createObjectURL(new Blob([content], { type: "text/markdown" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); }
  return <div className="page-shell mx-auto max-w-[1500px] px-4 pb-24 pt-8 md:px-8 md:pt-12"><section className="relative overflow-hidden rounded-[36px] border border-white/10 bg-[#081522]/90 p-6 shadow-[0_30px_100px_rgba(0,0,0,.32)] md:p-10"><div className="absolute -right-24 -top-24 h-96 w-96 rounded-full bg-cyan-400/10 blur-3xl" /><div className="relative grid gap-8 lg:grid-cols-[1fr_.7fr] lg:items-end"><div><div className="eyebrow">SciLoop / Director AI</div><h1 className="mt-5 max-w-4xl font-display text-5xl font-semibold leading-[.98] tracking-[-.06em] text-white md:text-7xl">One brain for the <span className="text-gradient">whole system.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-slate-300 md:text-lg">The Director does not make one more reel. It understands the discovery, coordinates the engines, critiques every version, and chooses the evidence-backed best result.</p><div className="mt-6 flex flex-wrap gap-2 text-[10px] uppercase tracking-[.16em] text-slate-500"><span className="rounded-full border border-cyan-200/20 px-3 py-2">Decision layer</span><span className="rounded-full border border-white/10 px-3 py-2">7 specialist reviewers</span><span className="rounded-full border border-white/10 px-3 py-2">10 × 10 creative search</span></div></div><div className="rounded-[26px] border border-cyan-200/15 bg-black/20 p-5"><div className="eyebrow">Direct a production</div><textarea value={discovery} onChange={(event) => setDiscovery(event.target.value)} rows={3} className="mt-4 w-full resize-none rounded-2xl border border-white/10 bg-white/[.04] p-4 text-sm leading-6 text-white outline-none focus:border-cyan-200/50" /><button onClick={runDirector} disabled={busy} className="mt-4 w-full rounded-xl bg-cyan-200 px-5 py-3 text-xs font-semibold text-slate-950 transition hover:bg-white disabled:opacity-60">{busy ? "Director is thinking…" : "Run Director AI"}</button></div></div></section>

    {!run ? <section className="mt-8 rounded-[30px] border border-white/10 bg-[#091321]/90 p-10 text-center"><div className="text-5xl text-cyan-100/50">◉</div><h2 className="mt-5 font-display text-2xl font-semibold text-white">A production decision, not a single generation</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-7 text-slate-500">Run Director AI to see the pipeline move from science understanding to knowledge graph, story search, asset routing, viral simulation, review, and final selection.</p></section> : <><section className="mt-8 rounded-[30px] border border-white/10 bg-[#091321]/90 p-5 md:p-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="eyebrow">Production pipeline</div><h2 className="mt-2 font-display text-2xl font-semibold text-white">{run.project.title}</h2></div><div className="text-right"><div className="font-display text-4xl font-semibold text-white">{run.variants.find((variant) => variant.id === run.selectedVariantId)?.scores.overall}<span className="text-base text-slate-500"> / 100</span></div><div className="font-mono text-[10px] uppercase tracking-[.15em] text-emerald-200">{run.selectedVariantId} selected</div></div></div><div className="mt-7 grid grid-cols-2 gap-2 md:grid-cols-5">{run.stages.map((stage) => <div key={stage.id} className={`rounded-xl border p-3 ${stage.status === "active" ? "border-cyan-200/35 bg-cyan-200/[.07]" : "border-white/8 bg-white/[.025]"}`}><div className="font-mono text-[9px] text-cyan-100/70">{stage.status === "active" ? "NOW" : "DONE"}</div><div className="mt-2 text-xs text-white">{stage.label}</div><div className="mt-1 text-[10px] text-slate-500">{stage.detail}</div></div>)}</div></section><div className="mt-5 flex flex-wrap gap-2 border-b border-white/10 pb-3">{(["pipeline", "variants", "reviews", "decisions"] as const).map((item) => <button key={item} onClick={() => setTab(item)} className={`rounded-full px-4 py-2 text-xs ${tab === item ? "bg-cyan-200/12 text-cyan-100" : "text-slate-500 hover:text-white"}`}>{item}</button>)}</div>
      {tab === "pipeline" && <div className="mt-5 grid gap-5 xl:grid-cols-[1fr_330px]"><section className="rounded-[30px] border border-white/10 bg-[#091321]/90 p-5 md:p-7"><div className="eyebrow">Director decision map</div><div className="mt-5 space-y-3">{run.decisions.map((decision) => <div key={decision.decision} className="grid gap-3 rounded-2xl border border-white/8 bg-white/[.025] p-4 md:grid-cols-[150px_1fr]"><div className="text-xs uppercase tracking-[.12em] text-slate-500">{decision.decision}</div><div><div className="text-sm font-medium text-white">{decision.choice}</div><p className="mt-1 text-xs leading-5 text-slate-400">{decision.reasoning}</p><div className="mt-2 text-[10px] text-cyan-100/70">Evidence: {decision.evidence}</div></div></div>)}</div></section><aside className="space-y-5"><section className="rounded-[26px] border border-white/10 bg-[#091321]/90 p-5"><div className="eyebrow">Cross-engine scores</div><div className="mt-5 space-y-4"><Score label="Viral simulation" value={run.simulation.metrics.overallViralScore} /><Score label="Knowledge branch" value={run.graph.novelty.branchScore} /><Score label="Reviewer consensus" value={Math.round(run.reviews.reduce((sum, review) => sum + review.score, 0) / run.reviews.length)} /><Score label="Selected production" value={run.variants.find((variant) => variant.id === run.selectedVariantId)?.scores.overall ?? 0} /></div></section><section className="rounded-[26px] border border-emerald-200/15 bg-emerald-200/[.04] p-5"><div className="eyebrow">Final recommendation</div><p className="mt-3 text-sm leading-6 text-emerald-100/80">{run.finalRecommendation.split("\n").slice(4, 7).join(" ")}</p></section></aside></div>}
      {tab === "variants" && <section className="mt-5 rounded-[30px] border border-white/10 bg-[#091321]/90 p-5 md:p-7"><div className="flex items-end justify-between"><div><div className="eyebrow">Creative search</div><h2 className="mt-2 font-display text-2xl font-semibold text-white">10 story variants · 100 hooks</h2></div><div className="font-mono text-[10px] text-slate-500">selected: {run.selectedVariantId}</div></div><div className="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-5">{run.variants.map((variant) => <div key={variant.id} className={`rounded-2xl border p-4 ${variant.recommended ? "border-cyan-200/35 bg-cyan-200/[.06]" : "border-white/8 bg-white/[.025]"}`}><div className="flex justify-between"><span className="font-mono text-xs text-cyan-100">{variant.id}</span><strong className="font-mono text-cyan-100">{variant.scores.overall}</strong></div><div className="mt-4 text-sm font-medium text-white">{variant.storyAngle}</div><div className="mt-1 text-xs text-slate-500">{variant.style} · {variant.audience}</div><div className="mt-4 text-xs leading-5 text-slate-300">{variant.selectedHook}</div><div className="mt-3 text-[10px] text-emerald-200/70">{variant.hooks.length} hooks evaluated</div></div>)}</div></section>}
      {tab === "reviews" && <section className="mt-5 rounded-[30px] border border-white/10 bg-[#091321]/90 p-5 md:p-7"><div className="eyebrow">Multi-agent review</div><h2 className="mt-2 font-display text-2xl font-semibold text-white">Specialists disagree. The Director resolves.</h2><div className="mt-6 grid gap-3 md:grid-cols-2">{run.reviews.map((review) => <div key={review.agent} className="rounded-2xl border border-white/8 bg-white/[.025] p-4"><div className="flex justify-between"><span className="text-sm text-white">{review.agent}</span><span className="font-mono text-cyan-100">{review.score}</span></div><div className="mt-3 text-[10px] uppercase tracking-[.12em] text-emerald-200">{review.verdict}</div><p className="mt-3 text-xs leading-5 text-slate-400">Strength: {review.strengths.join("; ")}</p><p className="mt-2 text-xs leading-5 text-slate-500">Improve: {review.weaknesses.join("; ")}</p></div>)}</div></section>}
      {tab === "decisions" && <section className="mt-5 rounded-[30px] border border-white/10 bg-[#091321]/90 p-5 md:p-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="eyebrow">Decision memory</div><h2 className="mt-2 font-display text-2xl font-semibold text-white">Why this version won.</h2></div><div className="flex flex-wrap gap-2">{Object.entries(run.outputs).map(([name, content]) => <button key={name} onClick={() => download(name, content)} className="rounded-full border border-white/10 px-3 py-2 text-[10px] text-slate-300 hover:border-cyan-200/30">Download {name}</button>)}</div></div><div className="mt-6 grid gap-5 md:grid-cols-2"><div className="rounded-2xl border border-emerald-200/15 bg-emerald-200/[.04] p-5"><div className="eyebrow">Reuse next time</div><p className="mt-3 text-sm leading-6 text-emerald-100/80">{run.learningMemory.reusablePattern}</p></div><div className="rounded-2xl border border-rose-200/15 bg-rose-200/[.04] p-5"><div className="eyebrow">Avoid next time</div><p className="mt-3 text-sm leading-6 text-rose-100/80">{run.learningMemory.avoidPattern}</p></div></div><div className="mt-6 space-y-3">{run.optimizationHistory.map((item) => <div key={item.iteration} className="flex flex-wrap items-center gap-4 border-b border-white/8 py-3"><span className="font-mono text-xs text-cyan-100">0{item.iteration}</span><span className="flex-1 text-sm text-white">{item.change}</span><span className="font-mono text-xs text-slate-400">{item.before} → {item.after}</span><span className="text-xs text-emerald-200">{item.result}</span></div>)}</div></section>}
    </>}
  </div>;
}
