import { createVisualRecipe } from "./visualRecipe.factory";
import type { VisualAtomType, VisualCertainty } from "./visualTypes";
import type { PredictiveCertainty, PredictiveSemanticKind, PredictiveVisualPackage } from "./predictiveVisual.types";
import { validatePredictiveVisualPackage } from "./predictiveVisual.validator";
import type { VisualRecipe } from "./visualRecipe.types";

function toVisualCertainty(certainty: PredictiveCertainty): VisualCertainty {
  return certainty;
}

function atomForKind(kind: PredictiveSemanticKind): VisualAtomType {
  if (kind === "signal") return "signal";
  if (kind === "unknown") return "uncertainty";
  if (kind === "variable") return "scale";
  if (kind === "risk") return "effect";
  if (kind === "condition") return "layer";
  return "node";
}

function layerForKind(kind: PredictiveSemanticKind) {
  if (kind === "evidence" || kind === "signal") return "evidence";
  if (kind === "outcome" || kind === "risk" || kind === "unknown") return "scenarios";
  return "causal-model";
}

/**
 * Deterministic compiler: a validated semantic package becomes a controlled
 * SciLoop recipe. No image, SVG, Canvas, or UI code is generated by an engine.
 */
export function compilePredictiveVisualPackage(pkg: PredictiveVisualPackage): VisualRecipe {
  const validation = validatePredictiveVisualPackage(pkg);
  if (!validation.ok) {
    throw new Error(`Cannot compile predictive visual package: ${validation.issues.map((entry) => entry.message).join(" ")}`);
  }

  const scenarioIds = pkg.scenarios.map((scenario) => scenario.id);
  return createVisualRecipe({
    id: `recipe-${pkg.id}`,
    title: pkg.title,
    concept: pkg.subject,
    summary: pkg.summary,
    metadata: {
      createdBy: "system",
      version: pkg.schemaVersion,
      source: `predictive-visual-package:${pkg.id}; engine:${pkg.provenance.engineId}@${pkg.provenance.engineVersion}`,
      confidence: 0.7,
    },
    difficulty: "intermediate",
    targetAudience: "general",
    visualType: pkg.scenarios.length > 1 ? "comparison" : "flow-system",
    pattern: "cause-effect",
    atomsUsed: ["node", "edge", "cause", "effect", "uncertainty", "timeline"],
    layers: [
      { id: "evidence", title: "Evidence", description: "Source-linked observations and signals.", depth: 0, atomsUsed: ["node", "signal"], visibleByDefault: true },
      { id: "causal-model", title: "Causal model", description: "Variables and relationships that shape the system.", depth: 1, atomsUsed: ["node", "cause", "edge", "scale"], visibleByDefault: true },
      { id: "scenarios", title: "Conditional scenarios", description: "Outcomes, risks, and unknowns under stated assumptions.", depth: 2, atomsUsed: ["effect", "uncertainty"], visibleByDefault: true },
    ],
    objects: pkg.nodes.map((node) => ({
      id: node.id,
      label: node.label,
      atom: atomForKind(node.kind),
      layerId: layerForKind(node.kind),
      description: node.description,
      evidenceIds: node.evidenceIds,
      semanticKind: node.kind,
      scenarioIds: node.scenarioIds,
      certainty: toVisualCertainty(node.certainty),
      importance: node.kind === "risk" || node.kind === "unknown" ? 0.9 : 0.7,
    })),
    relations: pkg.edges.map((edge) => ({
      id: edge.id,
      fromObjectId: edge.from,
      toObjectId: edge.to,
      atom: edge.kind === "causes" ? "cause" : edge.kind === "uncertain" ? "edge" : "effect",
      label: edge.label,
      strength: edge.strength,
      certainty: toVisualCertainty(edge.certainty),
      evidenceIds: edge.evidenceIds,
      scenarioIds: edge.scenarioIds,
    })),
    flows: [],
    transformations: [],
    feedbackLoops: [],
    timeline: {
      id: `timeline-${pkg.id}`,
      stages: pkg.scenarios.map((scenario) => ({
        id: scenario.id,
        label: scenario.title,
        description: `${scenario.classification}: ${scenario.summary}`,
        relatedObjectIds: pkg.nodes.filter((node) => node.scenarioIds?.includes(scenario.id)).map((node) => node.id),
      })),
    },
    interactions: [],
    motion: [],
    engineRecommendation: {
      primary: "react-tailwind",
      alternatives: ["svg-motion", "three-r3f"],
      reason: "SciLoop renders validated semantic primitives deterministically; spatial rendering is optional, not required.",
    },
    explanation: {
      simple: pkg.summary,
      detailed: `This model is evidence-linked and conditional. Assumptions: ${pkg.assumptions.join("; ") || "none recorded"}. Unknowns: ${pkg.unknowns.join("; ") || "none recorded"}.`,
      keyTakeaways: [...pkg.risks, ...pkg.unknowns].slice(0, 4),
      visualReadingOrder: ["Evidence", "Causal model", "Conditional scenarios"],
    },
    fallback: {
      title: "Evidence-linked concept map",
      description: "A readable map is always available when an advanced renderer is unavailable.",
      safeVisualType: "concept-map",
      messageForUser: "This is a conditional model, not a guaranteed prediction.",
    },
    assessment: {
      checksUnderstanding: true,
      expectedUserInsight: "The user can identify which variables, evidence, assumptions, and unknowns shape each scenario.",
      questions: ["Which relationship is evidence-linked?", "Which assumption would most change the scenario?"],
      successCriteria: ["Evidence, inference, and unknowns remain visibly distinct.", "The model can fall back to a readable concept map."],
    },
    tags: ["predictive-visual-package", pkg.provenance.engineId, ...scenarioIds],
  });
}
