import type { VisualAtom } from "./visualTypes";

/**
 * SciLoop visual atoms are the smallest controlled units of visual meaning.
 *
 * Future AI should select from these atoms instead of directly inventing SVG,
 * Canvas commands, or image prompts. The renderer can then decide how to draw
 * them while preserving stable meaning for the user.
 */
export const visualLanguageAtoms = [
  {
    id: "node",
    name: "Node",
    description: "Represents a concept, object, person, system, event, or idea.",
    visualMeaning: "A thing that can be named, inspected, related, or changed.",
    commonUses: ["concept maps", "actors", "events", "objects", "states"],
    suggestedVisualForm: "circle",
  },
  {
    id: "edge",
    name: "Edge",
    description: "Represents a relationship between two nodes.",
    visualMeaning: "A readable connection that explains how two things relate.",
    commonUses: ["dependency", "association", "influence", "reference"],
    suggestedVisualForm: "line",
  },
  {
    id: "layer",
    name: "Layer",
    description: "Represents hidden or visible levels of reality.",
    visualMeaning: "Depth, abstraction, or nested context behind a surface idea.",
    commonUses: ["microscopic to macroscopic views", "hidden systems", "abstraction levels"],
    suggestedVisualForm: "stacked-plane",
  },
  {
    id: "flow",
    name: "Flow",
    description: "Represents movement of information, energy, attention, money, force, or causality.",
    visualMeaning: "Something moves from a source to a receiver over time.",
    commonUses: ["energy transfer", "data movement", "causal chains", "economic exchange"],
    suggestedVisualForm: "stream",
  },
  {
    id: "field",
    name: "Field",
    description: "Represents distributed influence across an area or system.",
    visualMeaning: "A force or condition affects many things, not only one direct link.",
    commonUses: ["gravity", "magnetism", "risk zones", "social pressure", "attention fields"],
    suggestedVisualForm: "gradient-field",
  },
  {
    id: "timeline",
    name: "Timeline",
    description: "Represents ordered change across time.",
    visualMeaning: "A concept becomes understandable by seeing stages in sequence.",
    commonUses: ["history", "process stages", "evolution", "experiments", "cause over time"],
    suggestedVisualForm: "sequence",
  },
  {
    id: "scale",
    name: "Scale",
    description: "Represents size, scope, level, or magnitude.",
    visualMeaning: "The same idea changes meaning when viewed at a different scale.",
    commonUses: ["atom to planet", "individual to society", "local to global"],
    suggestedVisualForm: "scale-ladder",
  },
  {
    id: "transformation",
    name: "Transformation",
    description: "Represents before, process, and after.",
    visualMeaning: "A visible change caused by a mechanism.",
    commonUses: ["chemical change", "learning", "innovation", "state transitions"],
    suggestedVisualForm: "before-process-after",
  },
  {
    id: "cause",
    name: "Cause",
    description: "Represents the source condition or trigger that starts a change.",
    visualMeaning: "Why the system begins moving from one state to another.",
    commonUses: ["initial conditions", "triggers", "inputs", "root causes"],
    suggestedVisualForm: "cause-marker",
  },
  {
    id: "effect",
    name: "Effect",
    description: "Represents the visible result of a cause or transformation.",
    visualMeaning: "What changes because something else happened.",
    commonUses: ["outcomes", "consequences", "outputs", "visible results"],
    suggestedVisualForm: "effect-marker",
  },
  {
    id: "feedback",
    name: "Feedback",
    description: "Represents output affecting input.",
    visualMeaning: "The result loops back and changes future behavior.",
    commonUses: ["learning loops", "climate loops", "market cycles", "control systems"],
    suggestedVisualForm: "loop-arrow",
  },
  {
    id: "system",
    name: "System",
    description: "Represents a bounded group of related parts.",
    visualMeaning: "A whole made from interacting components.",
    commonUses: ["ecosystems", "machines", "economies", "organs", "platforms"],
    suggestedVisualForm: "system-boundary",
  },
  {
    id: "energy",
    name: "Energy",
    description: "Represents capacity to do work, drive change, or power motion.",
    visualMeaning: "The active resource that makes a process move.",
    commonUses: ["physics", "biology", "computation", "infrastructure"],
    suggestedVisualForm: "energy-pulse",
  },
  {
    id: "information",
    name: "Information",
    description: "Represents structured meaning, data, signal, or instruction.",
    visualMeaning: "A pattern that reduces uncertainty or guides behavior.",
    commonUses: ["AI", "neurons", "communication", "learning", "control"],
    suggestedVisualForm: "information-packet",
  },
  {
    id: "human-understanding",
    name: "Human Understanding",
    description: "Represents the learner's clarified mental model.",
    visualMeaning: "The moment where scattered input becomes usable meaning.",
    commonUses: ["learning outcomes", "explanations", "insight states", "summary layers"],
    suggestedVisualForm: "understanding-glow",
  },
  {
    id: "interaction",
    name: "Interaction",
    description: "Represents a user action that changes or reveals meaning.",
    visualMeaning: "The user participates in understanding by manipulating the model.",
    commonUses: ["sliders", "hover inspection", "dragging nodes", "timeline scrubbing"],
    suggestedVisualForm: "control-handle",
  },
  {
    id: "uncertainty",
    name: "Uncertainty",
    description: "Represents unknown, inferred, probabilistic, or weakly supported meaning.",
    visualMeaning: "The system is honest about what is not fully known.",
    commonUses: ["probability", "AI confidence", "hypotheses", "forecasting"],
    suggestedVisualForm: "uncertainty-haze",
  },
  {
    id: "pattern",
    name: "Pattern",
    description: "Represents repeated structure that can be recognized across examples.",
    visualMeaning: "A recurring form that helps the mind compress complexity.",
    commonUses: ["motifs", "periodicity", "templates", "laws", "classification"],
    suggestedVisualForm: "repeating-motif",
  },
  {
    id: "signal",
    name: "Signal",
    description: "Represents meaningful information extracted from noise.",
    visualMeaning: "The part of input that carries useful structure.",
    commonUses: ["sensing", "communication", "AI classification", "measurement"],
    suggestedVisualForm: "signal-beam",
  },
  {
    id: "noise",
    name: "Noise",
    description: "Represents random, irrelevant, distorted, or confusing input.",
    visualMeaning: "Unstructured input that must be filtered before understanding emerges.",
    commonUses: ["raw data", "confusion", "measurement error", "irrelevant detail"],
    suggestedVisualForm: "noise-cloud",
  },
] as const satisfies readonly VisualAtom[];

export type CoreVisualAtom = (typeof visualLanguageAtoms)[number];

