import { getFallbackEngines } from "./engineFallbacks";
import type { VisualEngine } from "./engine.types";

/**
 * Engines are tools, not the invention. SciLoop's invention is controlled
 * visual understanding: Visual Recipe -> Pattern -> Engine Router -> Safe Renderer.
 */
export const visualEngines: VisualEngine[] = [
  {
    id: "react-tailwind",
    name: "React + Tailwind",
    category: "layout",
    description: "Clean cards, dashboards, explanation panels, and simple layouts.",
    bestFor: ["Cards", "Dashboards", "Explanations", "Static concept layouts"],
    avoidFor: ["High-frequency animation", "Large particle fields", "3D worlds"],
    capabilities: ["cards", "dashboards"],
    strengths: [{ label: "Safe default", description: "Already supported by the current app shell." }],
    weaknesses: [{ label: "Limited motion", description: "Not ideal for rich continuous simulation." }],
    performanceProfile: { renderCost: "low", animationCost: "low", bestObjectCount: "few", notes: "Best for readable UI and low-risk fallbacks." },
    complexityLevel: "low",
    dependencyStatus: "installed",
    installed: true,
    supportedByCurrentProject: true,
    requiredDependencies: ["react", "tailwindcss"],
    fallbackEngineIds: getFallbackEngines("react-tailwind"),
    exampleUseCases: [{ label: "Simple concept card", description: "Static explanation panel.", visualTypes: ["concept-map", "comparison"], atoms: ["information"], keywords: ["card", "dashboard", "summary"] }],
    tags: ["safe", "ui", "dashboard", "cards"],
  },
  {
    id: "svg-motion",
    name: "SVG + Motion",
    category: "diagram",
    description: "Diagrams, arrows, nodes, cause-effect, transformations, and layered reality.",
    bestFor: ["Diagrams", "Arrows", "Nodes", "Transformations", "Layer reveal"],
    avoidFor: ["Massive object counts", "Heavy physics", "3D worlds"],
    capabilities: ["diagrams", "arrows", "nodes"],
    strengths: [{ label: "Precise semantics", description: "Excellent for controlled visual language atoms." }],
    weaknesses: [{ label: "Scale limits", description: "Large animated scenes should move to Canvas or GPU." }],
    performanceProfile: { renderCost: "low", animationCost: "medium", bestObjectCount: "few", notes: "Good for first-class explanatory diagrams." },
    complexityLevel: "low",
    dependencyStatus: "installed",
    installed: true,
    supportedByCurrentProject: true,
    requiredDependencies: ["react", "framer-motion or CSS/SVG"],
    fallbackEngineIds: getFallbackEngines("svg-motion"),
    exampleUseCases: [{ label: "Cause-effect diagram", description: "Nodes connected by directed arrows.", visualTypes: ["concept-map", "transformation", "layered-reality"], atoms: ["node", "edge", "cause", "effect"], keywords: ["diagram", "arrow", "cause", "effect"] }],
    tags: ["diagram", "svg", "motion", "arrows"],
  },
  {
    id: "canvas-2d",
    name: "Canvas 2D",
    category: "simulation",
    description: "Lightweight simulations, particles, waves, signals, and repeated motion.",
    bestFor: ["Particles", "Waves", "Signals", "Repeated motion"],
    avoidFor: ["Accessible text-heavy layouts", "SEO content", "Complex DOM controls"],
    capabilities: ["particles", "waves", "signals"],
    strengths: [{ label: "Fast repeated drawing", description: "Useful for many simple moving elements." }],
    weaknesses: [{ label: "Manual accessibility", description: "Semantic text and controls need companion UI." }],
    performanceProfile: { renderCost: "medium", animationCost: "medium", bestObjectCount: "many", notes: "Native browser API, no package needed." },
    complexityLevel: "medium",
    dependencyStatus: "native",
    installed: true,
    supportedByCurrentProject: true,
    requiredDependencies: [],
    fallbackEngineIds: getFallbackEngines("canvas-2d"),
    exampleUseCases: [{ label: "Signal or particle demo", description: "Continuous motion with modest object counts.", visualTypes: ["simulation", "signal-decomposition", "flow-system"], atoms: ["flow", "signal", "energy"], keywords: ["wave", "particle", "signal", "heat"] }],
    tags: ["canvas", "particles", "waves", "simulation"],
  },
  {
    id: "d3",
    name: "D3",
    category: "data",
    description: "Graphs, networks, trees, data relationships, and force layouts.",
    bestFor: ["Knowledge graphs", "Trees", "Force layouts", "Data relationships"],
    avoidFor: ["Simple static cards", "3D scenes"],
    capabilities: ["graphs", "trees", "nodes"],
    strengths: [{ label: "Data relationships", description: "Strong mapping from data structure to visual structure." }],
    weaknesses: [{ label: "Missing dependency", description: "D3 is not installed in the current project." }],
    performanceProfile: { renderCost: "medium", animationCost: "medium", bestObjectCount: "many", notes: "Good future choice for graph layouts." },
    complexityLevel: "medium",
    dependencyStatus: "missing",
    installed: false,
    supportedByCurrentProject: false,
    requiredDependencies: ["d3"],
    fallbackEngineIds: getFallbackEngines("d3"),
    exampleUseCases: [{ label: "Knowledge graph", description: "Concepts connected by semantic relationships.", visualTypes: ["network", "decision-tree"], atoms: ["node", "edge", "information"], keywords: ["graph", "tree", "network"] }],
    tags: ["graph", "network", "data", "tree"],
  },
  {
    id: "echarts",
    name: "ECharts",
    category: "data",
    description: "Normal charts, dashboards, statistics, and comparisons.",
    bestFor: ["Line charts", "Bar charts", "Dashboards", "Statistics"],
    avoidFor: ["Custom physics", "Game-like interaction"],
    capabilities: ["charts", "dashboards"],
    strengths: [{ label: "Charting", description: "Efficient for conventional business/science charts." }],
    weaknesses: [{ label: "Missing dependency", description: "ECharts is not installed." }],
    performanceProfile: { renderCost: "medium", animationCost: "medium", bestObjectCount: "many", notes: "Useful if Command 7 adds real chart dashboards." },
    complexityLevel: "medium",
    dependencyStatus: "missing",
    installed: false,
    supportedByCurrentProject: false,
    requiredDependencies: ["echarts"],
    fallbackEngineIds: getFallbackEngines("echarts"),
    exampleUseCases: [{ label: "Statistics dashboard", description: "Standard chart comparison.", visualTypes: ["comparison", "timeline"], atoms: ["scale", "information"], keywords: ["chart", "stats", "dashboard"] }],
    tags: ["chart", "dashboard", "statistics"],
  },
  {
    id: "lottie",
    name: "Lottie",
    category: "animation",
    description: "Prebuilt lightweight animations.",
    bestFor: ["Prepared animations", "Explainer loops", "Lightweight motion assets"],
    avoidFor: ["Generated simulations", "Data-driven graphs"],
    capabilities: ["prebuilt-animation"],
    strengths: [{ label: "Polished playback", description: "Good for authored motion assets." }],
    weaknesses: [{ label: "Missing dependency", description: "No Lottie runtime is installed." }],
    performanceProfile: { renderCost: "low", animationCost: "medium", bestObjectCount: "few", notes: "Future option for authored animations." },
    complexityLevel: "medium",
    dependencyStatus: "missing",
    installed: false,
    supportedByCurrentProject: false,
    requiredDependencies: ["lottie-react or lottie-web"],
    fallbackEngineIds: getFallbackEngines("lottie"),
    exampleUseCases: [{ label: "Prebuilt explainer", description: "Prepared animation for repeated concept intro.", visualTypes: ["transformation"], atoms: ["transformation"], keywords: ["lottie", "prebuilt", "animation"] }],
    tags: ["animation", "prebuilt"],
  },
  {
    id: "rive",
    name: "Rive",
    category: "animation",
    description: "Interactive character or icon animations.",
    bestFor: ["Interactive icons", "Characters", "State-machine animation"],
    avoidFor: ["Open-ended simulation", "Data graphs"],
    capabilities: ["interactive-animation"],
    strengths: [{ label: "Interactive states", description: "Good for authored interactive vector assets." }],
    weaknesses: [{ label: "Missing dependency", description: "Rive is not installed." }],
    performanceProfile: { renderCost: "low", animationCost: "medium", bestObjectCount: "few", notes: "Future option for expressive controls." },
    complexityLevel: "medium",
    dependencyStatus: "missing",
    installed: false,
    supportedByCurrentProject: false,
    requiredDependencies: ["@rive-app/react-canvas"],
    fallbackEngineIds: getFallbackEngines("rive"),
    exampleUseCases: [{ label: "Interactive icon", description: "Stateful animation around a control.", visualTypes: ["concept-map"], atoms: ["interaction"], keywords: ["rive", "character", "icon"] }],
    tags: ["animation", "interactive"],
  },
  {
    id: "pixijs",
    name: "PixiJS",
    category: "simulation",
    description: "Many animated 2D objects, particles, and game-like 2D visuals.",
    bestFor: ["Many sprites", "Particle fields", "Animated 2D scenes"],
    avoidFor: ["Text-heavy dashboards", "3D spatial worlds"],
    capabilities: ["particles", "games"],
    strengths: [{ label: "2D animation scale", description: "Handles more animated objects than DOM/SVG." }],
    weaknesses: [{ label: "Missing dependency", description: "PixiJS is not installed." }],
    performanceProfile: { renderCost: "medium", animationCost: "high", bestObjectCount: "many", notes: "Good future upgrade from Canvas." },
    complexityLevel: "high",
    dependencyStatus: "missing",
    installed: false,
    supportedByCurrentProject: false,
    requiredDependencies: ["pixi.js"],
    fallbackEngineIds: getFallbackEngines("pixijs"),
    exampleUseCases: [{ label: "Many particles", description: "Animated 2D field with many moving objects.", visualTypes: ["simulation", "flow-system"], atoms: ["flow", "energy"], keywords: ["many", "particles", "sprites"] }],
    tags: ["pixi", "particles", "2d"],
  },
  {
    id: "phaser",
    name: "Phaser",
    category: "game",
    description: "Learning games, interactive labs, scoring, missions, and levels.",
    bestFor: ["Games", "Missions", "Scoring", "Learning labs"],
    avoidFor: ["Simple articles", "Static diagrams"],
    capabilities: ["games", "particles"],
    strengths: [{ label: "Game loop", description: "Built for levels, missions, and scoring." }],
    weaknesses: [{ label: "Missing dependency", description: "Phaser is not installed." }],
    performanceProfile: { renderCost: "medium", animationCost: "high", bestObjectCount: "many", notes: "Future choice for lab games, not base explanations." },
    complexityLevel: "high",
    dependencyStatus: "missing",
    installed: false,
    supportedByCurrentProject: false,
    requiredDependencies: ["phaser"],
    fallbackEngineIds: getFallbackEngines("phaser"),
    exampleUseCases: [{ label: "Learning mission", description: "Interactive science game with score and levels.", visualTypes: ["simulation"], atoms: ["interaction", "effect"], keywords: ["game", "mission", "level"] }],
    tags: ["game", "lab", "mission"],
  },
  {
    id: "three-r3f",
    name: "Three.js / React Three Fiber",
    category: "spatial",
    description: "3D worlds, cosmic simulations, spatial concepts, molecules, and fields.",
    bestFor: ["3D worlds", "Spatial concepts", "Molecules", "Cosmic simulations"],
    avoidFor: ["Simple diagrams", "Text-first explanation"],
    capabilities: ["3d", "particles"],
    strengths: [{ label: "Spatial understanding", description: "Strong for 3D concepts where depth matters." }],
    weaknesses: [{ label: "Higher complexity", description: "Should be used only when 3D improves understanding." }],
    performanceProfile: { renderCost: "high", animationCost: "high", bestObjectCount: "many", notes: "Installed, but should be routed carefully." },
    complexityLevel: "high",
    dependencyStatus: "installed",
    installed: true,
    supportedByCurrentProject: true,
    requiredDependencies: ["three", "@react-three/fiber", "@react-three/drei"],
    fallbackEngineIds: getFallbackEngines("three-r3f"),
    exampleUseCases: [{ label: "Gravity field", description: "Spatial field or cosmic simulation.", visualTypes: ["field-influence", "simulation"], atoms: ["field", "energy"], keywords: ["3d", "spatial", "cosmic", "molecule"] }],
    tags: ["three", "3d", "spatial", "field"],
  },
  {
    id: "webgl",
    name: "WebGL",
    category: "gpu",
    description: "GPU-accelerated browser graphics.",
    bestFor: ["GPU graphics", "Custom shader visuals", "High object counts"],
    avoidFor: ["Basic diagrams", "UI-heavy layouts"],
    capabilities: ["particles", "gpu-compute"],
    strengths: [{ label: "GPU acceleration", description: "Mature browser GPU graphics path." }],
    weaknesses: [{ label: "Lower-level complexity", description: "More implementation work than Canvas or Three." }],
    performanceProfile: { renderCost: "high", animationCost: "high", bestObjectCount: "massive", notes: "Native API, but not a default renderer." },
    complexityLevel: "high",
    dependencyStatus: "native",
    installed: true,
    supportedByCurrentProject: true,
    requiredDependencies: [],
    fallbackEngineIds: getFallbackEngines("webgl"),
    exampleUseCases: [{ label: "GPU particle field", description: "High-performance browser graphics.", visualTypes: ["simulation"], atoms: ["flow", "energy"], keywords: ["webgl", "gpu", "shader"] }],
    tags: ["gpu", "webgl", "particles"],
  },
  {
    id: "webgpu-experimental",
    name: "WebGPU Experimental",
    category: "gpu",
    description: "Advanced frontier experiments, massive particles, and compute-style visuals.",
    bestFor: ["Massive particles", "Compute experiments", "Frontier GPU demos"],
    avoidFor: ["Production-only paths", "No-fallback experiences"],
    capabilities: ["gpu-compute", "particles"],
    strengths: [{ label: "Frontier compute", description: "Strong future path for massive visual computation." }],
    weaknesses: [{ label: "Experimental", description: "Must always have fallback." }],
    performanceProfile: { renderCost: "high", animationCost: "high", bestObjectCount: "massive", notes: "Experimental browser support only." },
    complexityLevel: "frontier",
    dependencyStatus: "experimental",
    installed: false,
    supportedByCurrentProject: false,
    requiredDependencies: [],
    fallbackEngineIds: getFallbackEngines("webgpu-experimental"),
    exampleUseCases: [{ label: "Particle frontier", description: "Massive compute-style visual experiment.", visualTypes: ["simulation"], atoms: ["flow", "energy"], keywords: ["webgpu", "frontier", "massive"] }],
    tags: ["webgpu", "experimental", "frontier"],
  },
  {
    id: "maplibre",
    name: "MapLibre",
    category: "map",
    description: "Maps, geography, and local/global problem solving.",
    bestFor: ["Maps", "Geography", "Local/global problems"],
    avoidFor: ["Non-geographic concepts", "Simple relationship diagrams"],
    capabilities: ["maps"],
    strengths: [{ label: "Open maps", description: "Good base for geographic visual understanding." }],
    weaknesses: [{ label: "Missing dependency", description: "MapLibre is not installed." }],
    performanceProfile: { renderCost: "medium", animationCost: "medium", bestObjectCount: "many", notes: "Future option for map labs." },
    complexityLevel: "high",
    dependencyStatus: "missing",
    installed: false,
    supportedByCurrentProject: false,
    requiredDependencies: ["maplibre-gl"],
    fallbackEngineIds: getFallbackEngines("maplibre"),
    exampleUseCases: [{ label: "Global problem map", description: "Geographic view of local and global impact.", visualTypes: ["network"], atoms: ["node", "flow"], keywords: ["map", "geography", "global"] }],
    tags: ["map", "geography", "global"],
  },
  {
    id: "deckgl",
    name: "deck.gl",
    category: "map",
    description: "Large geospatial data layers, movement flows, and global-scale visual data.",
    bestFor: ["Large map layers", "Movement flows", "Geospatial data"],
    avoidFor: ["Small local diagrams", "Non-map concepts"],
    capabilities: ["geospatial-layers", "maps"],
    strengths: [{ label: "Large geospatial layers", description: "Strong for heavy global data overlays." }],
    weaknesses: [{ label: "Missing dependency", description: "deck.gl is not installed." }],
    performanceProfile: { renderCost: "high", animationCost: "high", bestObjectCount: "massive", notes: "Future advanced geospatial renderer." },
    complexityLevel: "frontier",
    dependencyStatus: "missing",
    installed: false,
    supportedByCurrentProject: false,
    requiredDependencies: ["deck.gl", "maplibre-gl"],
    fallbackEngineIds: getFallbackEngines("deckgl"),
    exampleUseCases: [{ label: "Global data layers", description: "Large-scale movement and geospatial overlays.", visualTypes: ["network"], atoms: ["flow", "field"], keywords: ["deck", "geospatial", "layers"] }],
    tags: ["deckgl", "geospatial", "global"],
  },
];

export function getVisualEngine(engineId: VisualEngine["id"]) {
  return visualEngines.find((engine) => engine.id === engineId);
}
