import type { PhysicsVisualRecipe } from "./types";

const publicSvg: PhysicsVisualRecipe["publicRenderer"] = {
  enabled: true,
  preferred: "svg",
  alternatives: ["canvas-2d"],
  lazy: false,
  autoplay: false,
  reducedMotionSafe: true,
};

const canvas2d: PhysicsVisualRecipe["canvasRenderer"] = {
  enabled: true,
  preferred: "canvas-2d",
  alternatives: ["svg"],
  lazy: true,
  autoplay: false,
  reducedMotionSafe: true,
  maxParticles: 160,
};

const threeWorkbench: PhysicsVisualRecipe["threeRenderer"] = {
  enabled: true,
  preferred: "three-webgl",
  alternatives: ["canvas-2d", "webgpu-experimental"],
  lazy: true,
  autoplay: false,
  reducedMotionSafe: true,
  maxParticles: 800,
};

export const physicsVisualLanguageRecipes: PhysicsVisualRecipe[] = [
  {
    id: "physics.induction.v1",
    version: "1.0",
    subject: "electromagnetic-induction",
    title: "Changing magnetic flux induces current",
    summary: "Relative motion changes magnetic flux through a loop, producing an induced emf and current.",
    understandingGoal: "The user can connect relative motion to changing flux and then to induced current direction.",
    entities: [
      { id: "magnet", label: "Moving magnet", kind: "source", description: "The magnetic source whose relative motion changes the flux.", certainty: "known", visibleInFallback: true },
      { id: "field", label: "Magnetic field", kind: "field", description: "Field lines crossing the conducting loop.", certainty: "known", visibleInFallback: true },
      { id: "loop", label: "Conducting loop", kind: "object", description: "The boundary through which magnetic flux is measured.", certainty: "known", visibleInFallback: true },
      { id: "emf", label: "Induced emf", kind: "measurement", description: "Potential difference generated by changing flux.", certainty: "known", visibleInFallback: true },
      { id: "current", label: "Current direction", kind: "outcome", description: "The direction predicted by Faraday's and Lenz's laws.", certainty: "known", visibleInFallback: true },
    ],
    causalRelations: [
      { id: "motion-to-flux", from: "magnet", to: "field", kind: "changes", label: "changes flux", directionMeaning: "Increasing or decreasing field-through-loop over time." },
      { id: "flux-to-emf", from: "field", to: "emf", kind: "causes", label: "induces emf", directionMeaning: "The time rate of flux change produces emf." },
      { id: "emf-to-current", from: "emf", to: "current", kind: "causes", label: "drives current", directionMeaning: "The induced potential difference determines current when the loop is closed." },
    ],
    controlledVariable: { id: "magnet-velocity", label: "Magnet velocity", symbol: "v", unit: "m/s", valueType: "scalar", initialValue: 0.5, min: -2, max: 2, step: 0.1, description: "Relative velocity between magnet and loop." },
    measuredOutput: { id: "induced-emf", label: "Induced emf", symbol: "ε", unit: "V", valueType: "scalar", description: "Magnitude and sign of the induced potential difference." },
    quantities: [
      { id: "magnetic-flux", label: "Magnetic flux", symbol: "Φ", unit: "Wb", valueType: "scalar", description: "Field passing through the loop." },
      { id: "flux-rate", label: "Flux change rate", symbol: "dΦ/dt", unit: "Wb/s", valueType: "scalar", description: "The causal change that matters, not field presence alone." },
    ],
    evidence: [{ id: "faraday-measurement", label: "Coil voltage measurement", description: "A voltmeter records a voltage only while flux changes.", observable: "voltage across the loop", sourceType: "measurement", certainty: "known" }],
    uncertainty: [{ id: "sensor-noise", label: "Sensor noise", description: "Real voltage measurements contain noise around the predicted signal.", representation: "haze", appliesTo: ["induced-emf"] }],
    timeline: { progression: "continuous", timeMeaning: "Time controls relative motion, flux change, and the measured emf.", stages: [{ id: "motion", label: "Relative motion", description: "The magnet moves relative to the loop.", entityIds: ["magnet"] }, { id: "change", label: "Flux changes", description: "The field through the loop changes.", entityIds: ["field", "loop"] }, { id: "response", label: "Current appears", description: "The loop responds with emf and current.", entityIds: ["emf", "current"] }] },
    prediction: { prompt: "What happens when the magnet stops?", expectedOutcome: "The flux stops changing, so the induced emf falls to zero." },
    misconceptionGuard: "A stationary magnet can create a magnetic field without inducing emf; change in flux is the mechanism.",
    comprehensionQuestion: "If the magnet reverses direction, what happens to the current direction?",
    publicRenderer: publicSvg,
    canvasRenderer: canvas2d,
    threeRenderer: threeWorkbench,
    fallback: { title: "Motion → changing flux → induced current", description: "A magnet changes the field through a conducting loop; the loop responds with an induced voltage and current.", readingOrder: ["magnet", "field", "emf", "current"], accessibleSummary: "A moving magnet changes magnetic flux through a conducting loop, producing an induced voltage and current.", visualForm: "before-process-after" },
    sources: ["OpenStax University Physics, Faraday's Law", "OpenStax College Physics, Lenz's Law"],
  },
  {
    id: "physics.relativity.v1",
    version: "1.0",
    subject: "general-relativity",
    title: "Matter changes spacetime geometry",
    summary: "Mass-energy changes spacetime geometry, and free objects follow paths set by that geometry.",
    understandingGoal: "The user can distinguish mass-energy, curvature, geodesic motion, and an observable effect.",
    entities: [
      { id: "mass-energy", label: "Mass-energy", kind: "source", description: "The distribution that determines the local geometry in this model.", certainty: "known", visibleInFallback: true },
      { id: "geometry", label: "Spacetime geometry", kind: "field", description: "A simplified 2D representation of curvature.", certainty: "inferred", visibleInFallback: true },
      { id: "light-path", label: "Light path", kind: "object", description: "A geodesic path through the modeled geometry.", certainty: "known", visibleInFallback: true },
      { id: "lensing", label: "Gravitational lensing", kind: "outcome", description: "An observable distortion or magnification of light from a distant source.", certainty: "known", visibleInFallback: true },
    ],
    causalRelations: [
      { id: "mass-to-geometry", from: "mass-energy", to: "geometry", kind: "causes", label: "curves", directionMeaning: "The modeled mass-energy distribution changes the geometry." },
      { id: "geometry-to-path", from: "geometry", to: "light-path", kind: "influences", label: "sets geodesic", directionMeaning: "Free light follows the geometry rather than a Euclidean straight line." },
      { id: "path-to-lensing", from: "light-path", to: "lensing", kind: "causes", label: "produces lensing", directionMeaning: "The altered path changes the observed image." },
    ],
    controlledVariable: { id: "mass-energy-density", label: "Mass-energy density", symbol: "ρ", unit: "model units", valueType: "scalar", initialValue: 1, min: 0, max: 2, step: 0.1, description: "The illustrative source strength in the model." },
    measuredOutput: { id: "deflection-angle", label: "Light deflection", symbol: "θ", unit: "degrees", valueType: "scalar", description: "The modeled change in light-path direction." },
    quantities: [{ id: "curvature", label: "Curvature", symbol: "R", unit: "model units", valueType: "scalar", description: "A visual proxy for local geometric curvature." }],
    evidence: [{ id: "lensing-observation", label: "Observed lensing", description: "Distant light can be magnified and distorted by intervening mass.", observable: "image distortion and magnification", sourceType: "observation", certainty: "known" }],
    uncertainty: [{ id: "surface-analogy", label: "2D analogy limit", description: "A 2D curved surface is a teaching analogy, not literal spacetime.", representation: "confidence", appliesTo: ["geometry"] }],
    timeline: { progression: "continuous", timeMeaning: "The visual compares geometry and paths as source strength changes; it is not a time evolution of the universe.", stages: [{ id: "source", label: "Mass-energy", description: "Set the source strength.", entityIds: ["mass-energy"] }, { id: "curvature", label: "Geometry changes", description: "The modeled geometry responds.", entityIds: ["geometry"] }, { id: "observation", label: "Light is deflected", description: "The path and observed image change.", entityIds: ["light-path", "lensing"] }] },
    prediction: { prompt: "What happens when the modeled mass-energy increases?", expectedOutcome: "The model predicts stronger curvature and greater light-path deflection." },
    misconceptionGuard: "The curved surface is a 2D teaching analogy; gravity is not literally a downward force pulling objects into a sheet.",
    comprehensionQuestion: "Which part of the visual represents the cause, and which part represents the observable evidence?",
    publicRenderer: publicSvg,
    canvasRenderer: canvas2d,
    threeRenderer: threeWorkbench,
    fallback: { title: "Mass-energy → curvature → altered light path", description: "A mass-energy source changes modeled geometry, which changes the path of light and the image we observe.", readingOrder: ["mass-energy", "geometry", "light-path", "lensing"], accessibleSummary: "Mass-energy changes spacetime geometry; altered geometry changes light paths and can produce gravitational lensing.", visualForm: "field-map" },
    sources: ["NASA Hubble Gravitational Lenses", "Stanford Gravity Probe B"],
  },
  {
    id: "physics.higgs.v1",
    version: "1.0",
    subject: "higgs-field",
    title: "Particle coupling with the Higgs field",
    summary: "Particles interact with the Higgs field with different coupling strengths, contributing to their rest-mass properties.",
    understandingGoal: "The user can distinguish the field, particle coupling, mass property, and decay evidence.",
    entities: [
      { id: "higgs-field", label: "Higgs field", kind: "field", description: "A field present throughout the modeled space.", certainty: "known", visibleInFallback: true },
      { id: "particle", label: "Elementary particle", kind: "object", description: "A particle with a modeled coupling to the field.", certainty: "known", visibleInFallback: true },
      { id: "rest-mass", label: "Rest-mass property", kind: "state", description: "A property associated with the particle's interaction with the field.", certainty: "known", visibleInFallback: true },
      { id: "decay-evidence", label: "Decay evidence", kind: "evidence", description: "Observed decay products used to infer a short-lived particle and its mass.", certainty: "inferred", visibleInFallback: true },
    ],
    causalRelations: [
      { id: "field-to-coupling", from: "higgs-field", to: "particle", kind: "influences", label: "couples", directionMeaning: "The interaction strength differs by particle type." },
      { id: "coupling-to-mass", from: "particle", to: "rest-mass", kind: "changes", label: "contributes to", directionMeaning: "The visual represents coupling as a contribution to a particle property, not friction." },
      { id: "mass-to-evidence", from: "rest-mass", to: "decay-evidence", kind: "supports", label: "leaves evidence", directionMeaning: "Decay products support an inferred mass peak." },
    ],
    controlledVariable: { id: "coupling-strength", label: "Coupling strength", symbol: "g", unit: "model units", valueType: "scalar", initialValue: 0.6, min: 0, max: 1, step: 0.1, description: "An illustrative parameter for comparing particle-field interaction strength." },
    measuredOutput: { id: "invariant-mass", label: "Invariant-mass peak", symbol: "m", unit: "GeV/c²", valueType: "distribution", description: "A distribution feature inferred from decay products." },
    quantities: [{ id: "field-amplitude", label: "Field amplitude", symbol: "φ", unit: "model units", valueType: "scalar", description: "The background field value used by the visual model." }],
    evidence: [{ id: "decay-spectrum", label: "Decay-product spectrum", description: "A short-lived particle is inferred from patterns in its decay products and a statistical mass excess.", observable: "invariant-mass excess", sourceType: "experiment", certainty: "inferred" }],
    uncertainty: [{ id: "mass-peak", label: "Statistical uncertainty", description: "The signal is inferred from a distribution with background and uncertainty.", representation: "distribution", appliesTo: ["invariant-mass", "decay-evidence"] }],
    timeline: { progression: "ordered", timeMeaning: "The stages follow a conceptual chain from field interaction to experimental evidence, not a literal animation of a particle acquiring mass in time.", stages: [{ id: "field", label: "Field background", description: "The field is present throughout the modeled region.", entityIds: ["higgs-field"] }, { id: "interaction", label: "Particle coupling", description: "The particle interacts with the field.", entityIds: ["particle", "rest-mass"] }, { id: "evidence", label: "Decay evidence", description: "Decay products produce an inferential signal.", entityIds: ["decay-evidence"] }] },
    prediction: { prompt: "What should stronger coupling mean in this model?", expectedOutcome: "The displayed particle property changes, while the evidence remains a distribution rather than a directly visible object." },
    misconceptionGuard: "The Higgs field is not ordinary friction or drag, and the Higgs boson is inferred through decay products and statistics.",
    comprehensionQuestion: "Which part is directly measured, and which part is inferred from the measured distribution?",
    publicRenderer: publicSvg,
    canvasRenderer: canvas2d,
    threeRenderer: threeWorkbench,
    fallback: { title: "Field → coupling → particle property → evidence", description: "The visual separates the Higgs field, particle interaction, mass-related property, and the decay evidence used to infer a signal.", readingOrder: ["higgs-field", "particle", "rest-mass", "decay-evidence"], accessibleSummary: "Particles interact with the Higgs field; their coupling relates to a mass property, while experiments infer the Higgs boson from decay products and statistical evidence.", visualForm: "labeled-flow" },
    sources: ["CERN, The Higgs boson", "CERN, How the Higgs boson was discovered"],
  },
];

export function getPhysicsVisualLanguageRecipe(subject: PhysicsVisualRecipe["subject"] | string) {
  return physicsVisualLanguageRecipes.find((recipe) => recipe.subject === subject || recipe.id === subject);
}

