"use client";

import { useMemo, useState } from "react";
import { domainColors, type KnowledgeGraph, type KnowledgeNode } from "@/lib/knowledge-graph";

const starter = "NASA discovers a hidden ocean beneath an icy moon";
const domains = ["All", "Physics", "Mathematics", "Biology", "Chemistry", "AI", "Engineering", "Economics", "Civilization"] as const;

function GraphCanvas({ graph, selected, onSelect }: { graph: KnowledgeGraph; selected: KnowledgeNode | null; onSelect: (node: KnowledgeNode) => void }) {
  const lookup = useMemo(() => new Map(graph.nodes.map((node) => [node.id, node])), [graph.nodes]);
  return <svg viewBox="0 0 100 100" role="img" aria-label="Interactive scientific knowledge graph" className="h-[460px] w-full"><title>Scientific knowledge graph</title><desc>Nodes show domains connected by scientific relationships. Select a node to inspect it.</desc>{graph.edges.map((edge) => { const source = lookup.get(edge.source); const target = lookup.get(edge.target); if (!source || !target) return null; return <g key={`${edge.source}-${edge.target}`}><line x1={source.x} y1={source.y} x2={target.x} y2={target.y} stroke="rgba(165,243,252,.22)" strokeWidth=".35" strokeDasharray="1 1" /><text x={(source.x + target.x) / 2} y={(source.y + target.y) / 2} fill="rgba(203,213,225,.48)" fontSize="2.2" textAnchor="middle">{edge.relation}</text></g>; })}{graph.nodes.map((node) => <g key={node.id} onClick={() => onSelect(node)} className="cursor-pointer"><circle cx={node.x} cy={node.y} r={selected?.id === node.id ? 4.7 : node.novelty === "new" ? 4 : 3.2} fill={domainColors[node.domain]} fillOpacity={selected?.id === node.id ? 1 : .78} stroke={selected?.id === node.id ? "white" : "rgba(255,255,255,.32)"} strokeWidth={selected?.id === node.id ? .8 : .35} /><text x={node.x} y={node.y + 7} fill="white" fontSize="2.7" textAnchor="middle">{node.label.length > 22 ? `${node.label.slice(0, 20)}…` : node.label}</text><text x={node.x} y={node.y - 5} fill={domainColors[node.domain]} fontSize="2.1" textAnchor="middle">{node.domain}</text></g>)}</svg>;
}

export function KnowledgeGraphStudio() {
  const [query, setQuery] = useState(starter);
  const [graph, setGraph] = useState<KnowledgeGraph | null>(null);
  const [domain, setDomain] = useState<(typeof domains)[number]>("All");
  const [search, setSearch] = useState("");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const selected = graph?.nodes.find((node) => node.id === selectedId) ?? null;
  const visibleNodes = graph?.nodes.filter((node) => (domain === "All" || node.domain === domain) && node.label.toLowerCase().includes(search.toLowerCase())) ?? [];

  async function build() { setBusy(true); try { const response = await fetch("/api/knowledge-graph", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ discovery: query }) }); const payload = (await response.json()) as { graph?: KnowledgeGraph }; if (payload.graph) { setGraph(payload.graph); setSelectedId(payload.graph.nodes[0]?.id ?? null); } } finally { setBusy(false); } }
  function download(name: string, content: string) { const url = URL.createObjectURL(new Blob([content], { type: "text/plain" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); }

  return <div className="page-shell mx-auto max-w-[1500px] px-4 pb-24 pt-8 md:px-8 md:pt-12"><section className="relative overflow-hidden rounded-[36px] border border-white/10 bg-[#081522]/90 p-6 shadow-[0_30px_100px_rgba(0,0,0,.32)] md:p-10"><div className="absolute -right-20 -top-28 h-96 w-96 rounded-full bg-violet-400/10 blur-3xl" /><div className="relative grid gap-8 lg:grid-cols-[1fr_.75fr] lg:items-end"><div><div className="eyebrow">SciLoop / Knowledge Graph</div><h1 className="mt-5 max-w-4xl font-display text-5xl font-semibold leading-[.98] tracking-[-.06em] text-white md:text-7xl">Every discovery is a <span className="text-gradient">doorway.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-slate-300 md:text-lg">A reel is only one view of the idea. Build the connected graph behind it: theory, method, application, open problem, and civilization-scale consequence.</p></div><div className="rounded-[26px] border border-violet-200/15 bg-black/20 p-5"><div className="eyebrow">Graph a discovery</div><textarea value={query} onChange={(event) => setQuery(event.target.value)} rows={3} className="mt-4 w-full resize-none rounded-2xl border border-white/10 bg-white/[.04] p-4 text-sm leading-6 text-white outline-none focus:border-violet-200/50" /><button onClick={build} disabled={busy} className="mt-4 w-full rounded-xl bg-violet-200 px-5 py-3 text-xs font-semibold text-slate-950 transition hover:bg-white disabled:opacity-60">{busy ? "Mapping knowledge…" : "Build knowledge graph"}</button></div></div></section>

    {graph && <><section className="mt-8 grid gap-5 xl:grid-cols-[1fr_330px]"><div className="rounded-[30px] border border-white/10 bg-[#091321]/90 p-5 md:p-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="eyebrow">Connected knowledge</div><h2 className="mt-2 font-display text-2xl font-semibold text-white">{graph.title}</h2></div><div className="font-mono text-[10px] uppercase tracking-[.16em] text-violet-100">{graph.nodes.length} nodes · {graph.edges.length} relationships</div></div><div className="mt-5 overflow-hidden rounded-2xl border border-white/8 bg-[#07101d]"><GraphCanvas graph={{ ...graph, nodes: graph.nodes.map((node) => visibleNodes.some((item) => item.id === node.id) ? node : { ...node, x: -20, y: -20 }) }} selected={selected} onSelect={(node) => setSelectedId(node.id)} /></div><div className="mt-4 flex flex-wrap gap-2">{Object.entries(domainColors).map(([name, color]) => <span key={name} className="flex items-center gap-2 text-[10px] text-slate-400"><i className="h-2 w-2 rounded-full" style={{ backgroundColor: color }} />{name}</span>)}</div></div><aside className="space-y-5"><section className="rounded-[26px] border border-white/10 bg-[#091321]/90 p-5"><div className="eyebrow">Explore graph</div><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search nodes…" className="mt-4 w-full rounded-xl border border-white/10 bg-white/[.04] px-3 py-3 text-xs text-white outline-none" /><div className="mt-3 flex flex-wrap gap-2">{domains.map((item) => <button key={item} onClick={() => setDomain(item)} className={`rounded-full px-3 py-2 text-[10px] ${domain === item ? "bg-violet-200/15 text-violet-100" : "border border-white/10 text-slate-500"}`}>{item}</button>)}</div></section>{selected && <section className="rounded-[26px] border border-violet-200/15 bg-violet-200/[.04] p-5"><div className="eyebrow">Selected node</div><h3 className="mt-3 text-lg font-semibold text-white">{selected.label}</h3><div className="mt-2 text-[10px] uppercase tracking-[.14em]" style={{ color: domainColors[selected.domain] }}>{selected.domain} · {selected.kind}</div><p className="mt-4 text-sm leading-6 text-slate-400">{selected.description}</p><div className="mt-4 text-xs text-violet-100">{selected.novelty === "new" ? "✦ New branch detected" : "Connected to existing knowledge"}</div></section>}</aside></section>

    <section className="mt-8 rounded-[30px] border border-white/10 bg-[#091321]/90 p-5 md:p-7"><div className="flex flex-wrap items-end justify-between gap-5"><div><div className="eyebrow">Knowledge paths</div><h2 className="mt-2 font-display text-2xl font-semibold text-white">Choose how deeply to understand it.</h2></div><div className="font-mono text-[10px] uppercase tracking-[.16em] text-slate-500">historical timeline / {graph.novelty.branchScore} branch score</div></div><div className="mt-6 grid gap-3 md:grid-cols-3">{graph.learningPaths.map((path) => <div key={path.id} className="rounded-2xl border border-white/8 bg-white/[.025] p-4"><div className="flex justify-between"><span className="text-sm font-medium text-white">{path.title}</span><span className="font-mono text-[10px] text-cyan-100">{path.duration}</span></div><div className="mt-4 space-y-2">{path.steps.map((step, index) => <div key={step} className="flex gap-2 text-xs text-slate-400"><span className="font-mono text-cyan-100/70">0{index + 1}</span>{step}</div>)}</div><p className="mt-4 border-t border-white/8 pt-3 text-xs leading-5 text-slate-500">{path.outcome}</p></div>)}</div><div className="mt-7 overflow-x-auto"><div className="flex min-w-[650px] items-start gap-0">{graph.timeline.map((event, index) => <div key={event.year} className="relative flex-1 border-t border-cyan-200/25 pt-4"><span className="absolute -top-1.5 left-0 h-3 w-3 rounded-full border-2 border-cyan-200 bg-[#091321]" /><div className="font-mono text-[10px] text-cyan-100">{event.year}</div><div className="mt-1 text-xs text-white">{event.label}</div>{index < graph.timeline.length - 1 && <div className="absolute right-0 top-[-1px] text-cyan-100/50">→</div>}</div>)}</div></div></section>

    <section className="mt-8 grid gap-5 lg:grid-cols-[1fr_1fr]"><div className="rounded-[30px] border border-white/10 bg-[#091321]/90 p-5 md:p-7"><div className="eyebrow">Novelty detection</div><h2 className="mt-2 font-display text-2xl font-semibold text-white">Where this discovery changes the graph.</h2><div className="mt-5 space-y-3 text-sm">{graph.novelty.newRelationships.map((item) => <div key={item} className="rounded-xl border border-emerald-200/15 bg-emerald-200/[.04] p-3 text-emerald-100">+ {item}</div>)}{graph.novelty.knowledgeGaps.map((item) => <div key={item} className="rounded-xl border border-amber-200/15 bg-amber-200/[.04] p-3 text-amber-100">? {item}</div>)}</div></div><div className="rounded-[30px] border border-white/10 bg-[#091321]/90 p-5 md:p-7"><div className="eyebrow">Civilization impact</div><h2 className="mt-2 font-display text-2xl font-semibold text-white">One signal, many consequences.</h2><div className="mt-5 space-y-4">{graph.civilizationImpact.map((impact) => <div key={impact.domain}><div className="flex justify-between text-xs"><span className="text-slate-300">{impact.domain}</span><span className="font-mono text-cyan-100">{impact.impact}</span></div><div className="mt-2 h-1.5 rounded-full bg-white/8"><div className="h-full rounded-full bg-gradient-to-r from-cyan-300 to-violet-400" style={{ width: `${impact.impact}%` }} /></div><p className="mt-1 text-[11px] text-slate-500">{impact.explanation}</p></div>)}</div></div></section>

    <section className="mt-8 rounded-[30px] border border-white/10 bg-[#091321]/90 p-5 md:p-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="eyebrow">Generated outputs</div><h2 className="mt-2 font-display text-2xl font-semibold text-white">Ready for reels, simulations, and learning.</h2></div><div className="flex flex-wrap gap-2">{Object.entries(graph.outputs).map(([name, content]) => <button key={name} onClick={() => download(`${name}.md`, content)} className="rounded-full border border-white/10 px-3 py-2 text-[10px] text-slate-300 hover:border-cyan-200/30">Download {name}</button>)}</div></div></section></>}
  </div>;
}
