"use client";

import { useState } from "react";
import type { FormEvent } from "react";

import type { InnovationRecord } from "@/data/innovations";
import { PossibilityEnginePanel } from "@/components/innovations/possibility-engine-panel";

const humanityTimeline = [
  ["1905", "Einstein", "Relativity changes how humanity sees time and space."],
  ["1947", "Transistor", "Information becomes smaller, faster, and more widely available."],
  ["1969", "Moon landing", "A planetary species reaches another world."],
  ["1989", "World Wide Web", "Human knowledge becomes globally addressable."],
  ["2012", "CRISPR", "Biology becomes increasingly programmable."],
  ["2022", "ChatGPT", "Language becomes an interface to machine intelligence."],
  ["Today", "Live frontier", "The next chapter is still being written."],
] as const;

export function InnovationExplorer({ innovation }: { innovation: InnovationRecord }) {
  const [saved, setSaved] = useState(false);
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState("Ask about the mechanism, evidence, people, or future of this innovation.");
  const [asking, setAsking] = useState(false);
  const [shared, setShared] = useState(false);
  const [visualMode, setVisualMode] = useState("mechanism");
  const [futureYear, setFutureYear] = useState(2030);
  const [possibilityMode, setPossibilityMode] = useState(false);

  function save() { localStorage.setItem(`sciloop-saved-${innovation.slug}`, "true"); setSaved(true); }
  async function share() { try { await navigator.clipboard.writeText(window.location.href); setShared(true); window.setTimeout(() => setShared(false), 1800); } catch { setShared(false); } }
  async function ask(event: FormEvent) { event.preventDefault(); if (!question.trim()) return; setAsking(true); setAnswer("SciLoop AI is tracing this question through the innovation story…"); try { const response = await fetch("/api/kernel/plan", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ input: `${question.trim()} Context: ${innovation.title}. ${innovation.mechanism}` }) }); const data = await response.json() as { plan?: { strategy?: string; steps?: { label: string }[] } }; setAnswer(`${data.plan?.strategy ?? "evidence-first exploration"}. ${data.plan?.steps?.map((step) => step.label).join(" → ") ?? "Compare the mechanism, evidence, and future scenarios."}`); } catch { setAnswer("The AI layer is warming up. Start with the mechanism above, then return to ask again."); } finally { setAsking(false); setQuestion(""); } }

  return <main className={`page-shell pb-20 pt-5 md:pt-12 ${possibilityMode ? "possibility-focus" : ""}`}>
    <section className="innovation-detail-hero rounded-[40px] border border-white/10 px-6 py-10 md:px-12 md:py-14"><div className="eyebrow">Live innovation · {innovation.field}</div><h1 className="mt-5 max-w-5xl font-display text-4xl font-semibold leading-tight tracking-[-0.04em] text-white md:text-6xl">{innovation.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">{innovation.summary}</p><div className="mt-8 flex flex-wrap gap-3"><button type="button" onClick={save} className="rounded-full bg-white px-5 py-2.5 text-sm font-semibold text-slate-950">{saved ? "Saved ✓" : "Save innovation"}</button><button type="button" onClick={share} className="rounded-full border border-white/15 px-5 py-2.5 text-sm text-white">{shared ? "Link copied ✓" : "Share story"}</button><span className="rounded-full border border-cyan-200/15 px-5 py-2.5 text-sm text-cyan-100">{innovation.date}</span></div></section>
    <PossibilityEnginePanel innovation={innovation} onOpenChange={setPossibilityMode} />

    <section className="detail-section grid gap-6 lg:grid-cols-[1.05fr_.95fr]"><div><div className="eyebrow">01 · Quick understanding</div><h2 className="detail-heading">The idea in 30 seconds.</h2><p className="detail-copy">{innovation.mechanism}</p><div className="mt-7 grid gap-3">{innovation.facts.map((fact) => <div key={fact} className="fact-row"><span className="text-cyan-200">✦</span><span>{fact}</span></div>)}</div></div><div className="visual-explanation legacy-visual-section rounded-[30px] border border-cyan-200/15 p-5"><div className="eyebrow">Visual explanation</div><svg className="mt-5 w-full" viewBox="0 0 520 270" role="img" aria-label={`Diagram showing how ${innovation.title} works`}><defs><linearGradient id="flow" x1="0" x2="1"><stop stopColor="#67e8f9" /><stop offset="1" stopColor="#a78bfa" /></linearGradient></defs><path d="M52 135 C150 40 220 230 310 135 S430 40 480 135" fill="none" stroke="url(#flow)" strokeDasharray="5 8" strokeWidth="3" /><circle cx="82" cy="135" r="28" fill="#0e7490" opacity=".7" /><circle cx="260" cy="135" r="40" fill="#312e81" opacity=".8" /><circle cx="445" cy="135" r="28" fill="#92400e" opacity=".7" /><text x="82" y="140" fill="white" fontSize="13" textAnchor="middle">Signal</text><text x="260" y="140" fill="white" fontSize="13" textAnchor="middle">Mechanism</text><text x="445" y="140" fill="white" fontSize="13" textAnchor="middle">Future</text><text x="260" y="225" fill="#94a3b8" fontSize="12" textAnchor="middle">cause → transformation → consequence</text></svg></div></section>

    <section className="detail-section"><div className="eyebrow">02 · The story behind the signal</div><h2 className="detail-heading">History, people, and the technology.</h2><div className="mt-8 grid gap-8 lg:grid-cols-[1.2fr_.8fr]"><div className="timeline">{innovation.timeline.map((item) => <div key={item.year} className="timeline-item"><div className="timeline-year">{item.year}</div><div><h3 className="font-display text-xl font-semibold text-white">{item.label}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{item.detail}</p></div></div>)}</div><div className="space-y-6"><div className="detail-card"><div className="eyebrow">Scientists behind it</div><div className="mt-4 space-y-4">{innovation.scientists.map((scientist) => <div key={scientist.name}><div className="font-medium text-white">{scientist.name}</div><div className="text-sm text-slate-500">{scientist.role}</div></div>)}</div></div><div className="detail-card"><div className="eyebrow">Organizations</div><div className="mt-4 flex flex-wrap gap-2">{innovation.organizations.map((organization) => <span key={organization} className="chip rounded-full px-3 py-1.5 text-xs">{organization}</span>)}</div></div></div></div></section>

    <section className="detail-section grid gap-6 lg:grid-cols-2"><div><div className="eyebrow">03 · Technology breakdown</div><h2 className="detail-heading">The system, piece by piece.</h2><div className="mt-6 space-y-3">{innovation.technology.map((item, index) => <div key={item.label} className="technology-row"><span className="font-mono text-xs text-cyan-200/60">0{index + 1}</span><div><div className="font-medium text-white">{item.label}</div><p className="mt-1 text-sm leading-6 text-slate-400">{item.detail}</p></div></div>)}</div></div><div><div className="eyebrow">Related innovations</div><h2 className="detail-heading">The nearby ideas.</h2><div className="mt-6 flex flex-wrap gap-3">{innovation.related.map((item) => <span key={item} className="related-pill">{item} ↗</span>)}</div></div></section>

    <section className="detail-section legacy-future-section"><div className="eyebrow">04 · Imagine beyond</div><h2 className="detail-heading">What happens if this succeeds?</h2><div className="mt-7 grid gap-4 md:grid-cols-3">{innovation.futures.map((future) => <div key={future.label} className={`future-card future-${future.tone}`}><div className="font-display text-xl font-semibold text-white">{future.label}</div><p className="mt-3 text-sm leading-7 text-slate-300">{future.detail}</p></div>)}</div></section>

    <section className="detail-section ai-discussion rounded-[30px] border border-violet-200/15 p-6 md:p-8"><div className="eyebrow">05 · AI discussion</div><h2 className="detail-heading">Ask a better question.</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-400">Use SciLoop AI to connect this breakthrough to mechanisms, history, applications, and open problems.</p><form onSubmit={ask} className="mt-6 flex flex-col gap-3 sm:flex-row"><input value={question} onChange={(event) => setQuestion(event.target.value)} className="min-h-12 flex-1 rounded-2xl border border-white/10 bg-black/20 px-4 text-sm text-white outline-none placeholder:text-slate-600 focus:border-violet-200/50" placeholder="How could this change medicine, energy, or computing?" /><button disabled={asking} className="min-h-12 rounded-2xl bg-white px-5 text-sm font-semibold text-slate-950 disabled:opacity-60">{asking ? "Thinking…" : "Ask SciLoop"}</button></form><div className="mt-5 rounded-2xl border border-white/10 bg-black/15 p-4 text-sm leading-7 text-slate-300">{answer}</div></section>
    <section className="detail-section legacy-visual-section visual-engine-section"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="eyebrow">Visual engine</div><h2 className="detail-heading">See the idea move.</h2></div><div className="flex gap-2">{[["mechanism", "How it works"], ["system", "System view"], ["impact", "Impact view"]].map(([id, label]) => <button key={id} type="button" onClick={() => setVisualMode(id)} className={`rounded-full border px-3 py-2 text-xs ${visualMode === id ? "border-cyan-200/40 bg-cyan-200/10 text-white" : "border-white/10 text-slate-400"}`}>{label}</button>)}</div></div><div className="visual-engine-stage mt-7"><div className="visual-engine-orbit" aria-hidden="true" /><div className={`visual-engine-core visual-engine-${visualMode}`}><span className="visual-engine-particle particle-a" /><span className="visual-engine-particle particle-b" /><span className="visual-engine-particle particle-c" /><div className="visual-engine-label">{visualMode === "mechanism" ? "Signal → mechanism → result" : visualMode === "system" ? "Connected scientific system" : "A possibility entering the world"}</div></div></div></section>

    <section className="detail-section legacy-visual-section"><div className="eyebrow">06 · Innovation Universe</div><h2 className="detail-heading">Follow the living system beneath the breakthrough.</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-400">Every innovation is a doorway into the ideas, people, organizations, and open problems that made it possible.</p><div className="technology-graph mt-8">{innovation.technology.map((item, index) => <div key={item.label} className="technology-graph-node"><span className="font-mono text-xs text-cyan-200/60">0{index + 1}</span><strong>{item.label}</strong><small>{item.detail}</small>{index < innovation.technology.length - 1 && <span className="technology-graph-arrow" aria-hidden="true">↓</span>}</div>)}</div><div className="mt-5 flex flex-wrap justify-center gap-2 text-xs text-slate-500"><span className="related-pill">Scientists</span><span className="related-pill">Organizations</span><span className="related-pill">Future</span><span className="related-pill">Open problems</span></div></section>

    <section className="detail-section"><div className="eyebrow">07 · Humanity timeline</div><h2 className="detail-heading">The long arc of invention.</h2><div className="humanity-timeline mt-8">{humanityTimeline.map(([year, title, detail]) => <div key={year} className="humanity-timeline-item"><div className="font-mono text-xs text-cyan-200/70">{year}</div><div><h3 className="font-display text-lg font-semibold text-white">{title}</h3><p className="mt-1 max-w-xs text-sm leading-6 text-slate-500">{detail}</p></div></div>)}</div></section>

    <section className="detail-section legacy-future-section future-forecast rounded-[30px] border border-amber-200/15 p-6 md:p-8"><div className="eyebrow">08 · Future possibilities</div><div className="flex flex-wrap items-end justify-between gap-5"><div><h2 className="detail-heading">Move the possibility forward.</h2><p className="mt-3 max-w-xl text-sm leading-7 text-slate-400">A possibility is not a prediction. It is a question about which conditions humanity chooses to create.</p></div><div className="font-display text-5xl font-semibold text-amber-100">{futureYear}</div></div><input aria-label="Future possibility stage" type="range" min="2030" max="2050" step="10" value={futureYear} onChange={(event) => setFutureYear(Number(event.target.value))} className="mt-8 w-full accent-amber-200" /><div className="future-stage-labels mt-3 flex justify-between text-[10px] uppercase tracking-[0.16em] text-slate-500"><span>Near future</span><span>Emerging</span><span>Transformative</span><span>Civilization scale</span></div><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="future-card future-positive"><div className="flex items-center justify-between"><div className="font-display text-xl font-semibold text-white">Possible future</div><span className="probability">72%</span></div><p className="mt-3 text-sm leading-7 text-slate-300">By {futureYear}, the strongest version of this innovation changes what is possible for millions of people.</p></div><div className="future-card future-caution"><div className="flex items-center justify-between"><div className="font-display text-xl font-semibold text-white">Civilization impact</div><span className="probability">48%</span></div><p className="mt-3 text-sm leading-7 text-slate-300">Impact depends on access, safety, energy, governance, and whether the system scales beyond the lab.</p></div><div className="future-card future-open"><div className="flex items-center justify-between"><div className="font-display text-xl font-semibold text-white">Open problems</div><span className="probability">∞</span></div><p className="mt-3 text-sm leading-7 text-slate-300">What must be solved next to move this possibility from a signal to a new normal?</p></div></div></section>
  </main>;
}
