import type { VisualTechDemo } from "./techLab.types";

export const sharedTechLabConcept = "Raw Information -> Layered Reality -> Human Understanding";

export const techCapabilityCategories = [
  "Concept cards",
  "Diagrams",
  "Flows",
  "Timelines",
  "Charts",
  "Knowledge graphs",
  "Particles",
  "Game labs",
  "3D worlds",
  "Maps",
  "GPU experiments",
] as const;

const fallbackScores = Object.fromEntries(
  techCapabilityCategories.map((category) => [category, "not-ideal"]),
) as VisualTechDemo["capabilityScores"];

function scores(input: Partial<VisualTechDemo["capabilityScores"]>): VisualTechDemo["capabilityScores"] {
  const merged = { ...fallbackScores };
  Object.entries(input).forEach(([category, value]) => {
    if (value) {
      merged[category] = value;
    }
  });
  return merged;
}

/**
 * This lab compares rendering technologies. Engines are tools, not the
 * invention. SciLoop's invention is visual understanding, so the same concept
 * is used across demos for a fair comparison.
 */
export const visualTechDemos: VisualTechDemo[] = [
  {
    id: "react-tailwind",
    engineId: "react-tailwind",
    name: "React + Tailwind",
    description: "Layered cards for clean explanations and dashboards.",
    bestFor: ["Concept cards", "Dashboards", "Explanation panels"],
    notBestFor: ["Particles", "3D worlds", "GPU experiments"],
    demoStatus: "ready-now",
    demoMode: "live",
    installed: true,
    installStatus: "installed",
    dependencyName: "react, tailwindcss",
    primaryUseCase: { label: "Layered cards", description: "Raw information is organized into readable layers." },
    fallbackTech: [],
    performanceLevel: "low",
    interactionLevel: "low",
    learningValue: "Excellent for readable conceptual scaffolding.",
    recommendedForSciLoop: "use-now",
    notes: "Best default for safe Visual OS panels.",
    comparison: { clarity: 9, performance: 9, interaction: 4, complexity: 2, dependencyCost: 1, bestVisualPattern: "Compression of Complexity", bestSciLoopUseCase: "Explanation panels" },
    capabilityScores: scores({ "Concept cards": "excellent", Diagrams: "possible", Timelines: "good", Charts: "possible" }),
    routerConceptHint: "simple concept card dashboard explanation",
  },
  {
    id: "svg",
    engineId: "svg-motion",
    name: "SVG",
    description: "Static nodes, arrows, layers, and semantic diagrams.",
    bestFor: ["Diagrams", "Cause-effect", "Layered reality"],
    notBestFor: ["Large particle counts", "Game labs"],
    demoStatus: "ready-now",
    demoMode: "live",
    installed: true,
    installStatus: "native",
    primaryUseCase: { label: "Nodes and arrows", description: "Noise becomes signal, then understanding." },
    fallbackTech: ["react-tailwind"],
    performanceLevel: "low",
    interactionLevel: "low",
    learningValue: "Excellent for exact visual-language semantics.",
    recommendedForSciLoop: "use-now",
    notes: "Native browser SVG is already enough for many Visual Engine recipes.",
    comparison: { clarity: 9, performance: 8, interaction: 5, complexity: 3, dependencyCost: 1, bestVisualPattern: "Cause -> Effect", bestSciLoopUseCase: "Node-and-arrow explanations" },
    capabilityScores: scores({ Diagrams: "excellent", Flows: "good", Timelines: "good", "Knowledge graphs": "possible" }),
    routerConceptHint: "diagram nodes arrows layered reality cause effect",
  },
  {
    id: "svg-motion",
    engineId: "svg-motion",
    name: "SVG + Motion",
    description: "Animated information flow through controlled diagram layers.",
    bestFor: ["Animated diagrams", "Transformations", "Flows"],
    notBestFor: ["Massive simulation", "Game physics"],
    demoStatus: "ready-now",
    demoMode: "live",
    installed: true,
    installStatus: "installed",
    dependencyName: "framer-motion available, CSS/SVG fallback used here",
    primaryUseCase: { label: "Animated flow", description: "A signal moves from raw data to understanding." },
    fallbackTech: ["svg", "react-tailwind"],
    performanceLevel: "medium",
    interactionLevel: "medium",
    learningValue: "Adds time and transformation without heavy rendering.",
    recommendedForSciLoop: "use-now",
    notes: "Useful before Canvas when motion is diagrammatic rather than simulated.",
    comparison: { clarity: 9, performance: 7, interaction: 6, complexity: 4, dependencyCost: 2, bestVisualPattern: "Random -> Organized", bestSciLoopUseCase: "Flow explanations" },
    capabilityScores: scores({ Diagrams: "excellent", Flows: "excellent", Timelines: "good", Particles: "possible" }),
    routerConceptHint: "animated diagram flow transformation",
  },
  {
    id: "css-animation",
    engineId: "react-tailwind",
    name: "CSS Animation",
    description: "Small declarative motion for pulses, states, and UI feedback.",
    bestFor: ["Pulses", "Status motion", "Simple signal movement"],
    notBestFor: ["Simulation", "Data layouts"],
    demoStatus: "safe-fallback",
    demoMode: "live",
    installed: true,
    installStatus: "native",
    primaryUseCase: { label: "Signal pulse", description: "A pulse travels through three understanding stages." },
    fallbackTech: ["react-tailwind"],
    performanceLevel: "low",
    interactionLevel: "low",
    learningValue: "Good for lightweight attention guidance.",
    recommendedForSciLoop: "use-as-fallback",
    notes: "Use sparingly so motion stays meaningful.",
    comparison: { clarity: 7, performance: 9, interaction: 3, complexity: 2, dependencyCost: 1, bestVisualPattern: "Weak Signal -> Strong Signal", bestSciLoopUseCase: "Small affordance motion" },
    capabilityScores: scores({ "Concept cards": "good", Flows: "possible", Timelines: "possible" }),
    routerConceptHint: "simple concept card pulse animation",
  },
  {
    id: "canvas-2d",
    engineId: "canvas-2d",
    name: "Canvas 2D",
    description: "Lightweight particles, waves, signals, and repeated motion.",
    bestFor: ["Particles", "Signals", "Waves", "Light simulation"],
    notBestFor: ["Text-heavy layouts", "Accessible content by itself"],
    demoStatus: "ready-now",
    demoMode: "live",
    installed: true,
    installStatus: "native",
    primaryUseCase: { label: "Noise organizing", description: "Particles move from random noise into a signal line." },
    fallbackTech: ["svg-motion", "react-tailwind"],
    performanceLevel: "medium",
    interactionLevel: "medium",
    learningValue: "Best safe path for lightweight dynamic systems.",
    recommendedForSciLoop: "use-now",
    notes: "Keep particle counts modest and stop animation on unmount.",
    comparison: { clarity: 8, performance: 8, interaction: 6, complexity: 5, dependencyCost: 1, bestVisualPattern: "Random -> Organized", bestSciLoopUseCase: "Signal and particle demos" },
    capabilityScores: scores({ Flows: "good", Particles: "excellent", "GPU experiments": "possible" }),
    routerConceptHint: "signal wave particles raw information organizing",
  },
  {
    id: "d3",
    engineId: "d3",
    name: "D3",
    description: "Future use for knowledge graphs, trees, relationships, and force layouts.",
    bestFor: ["Knowledge graphs", "Trees", "Data relationships"],
    notBestFor: ["Simple cards", "Game labs"],
    demoStatus: "future-upgrade",
    demoMode: "placeholder",
    installed: false,
    installStatus: "missing",
    dependencyName: "d3",
    primaryUseCase: { label: "Concept graph", description: "Would show raw information nodes connected into understanding." },
    fallbackTech: ["svg", "react-tailwind"],
    performanceLevel: "medium",
    interactionLevel: "medium",
    learningValue: "Strong future option for concept networks.",
    recommendedForSciLoop: "evaluate-later",
    notes: "Do not add until graph layout needs become real.",
    comparison: { clarity: 8, performance: 7, interaction: 7, complexity: 7, dependencyCost: 6, bestVisualPattern: "Knowledge Graph", bestSciLoopUseCase: "Concept relationships" },
    capabilityScores: scores({ Diagrams: "good", "Knowledge graphs": "excellent", Charts: "good" }),
    routerConceptHint: "knowledge graph network tree relationships",
  },
  {
    id: "echarts",
    engineId: "echarts",
    name: "ECharts",
    description: "Future use for dashboards, charts, and comparison visuals.",
    bestFor: ["Charts", "Dashboards", "Statistics"],
    notBestFor: ["Particles", "3D worlds"],
    demoStatus: "future-upgrade",
    demoMode: "placeholder",
    installed: false,
    installStatus: "missing",
    dependencyName: "echarts",
    primaryUseCase: { label: "Understanding dashboard", description: "Would quantify clarity across stages." },
    fallbackTech: ["react-tailwind", "svg"],
    performanceLevel: "medium",
    interactionLevel: "medium",
    learningValue: "Useful when SciLoop needs standard charts.",
    recommendedForSciLoop: "evaluate-later",
    notes: "Current lab can use cards until real metrics need charts.",
    comparison: { clarity: 7, performance: 8, interaction: 6, complexity: 5, dependencyCost: 5, bestVisualPattern: "Comparison", bestSciLoopUseCase: "Metric dashboards" },
    capabilityScores: scores({ Charts: "excellent", "Concept cards": "possible", Timelines: "good" }),
    routerConceptHint: "chart statistics dashboard comparison",
  },
  {
    id: "lottie",
    engineId: "lottie",
    name: "Lottie",
    description: "Future use for prebuilt lightweight explainer animations.",
    bestFor: ["Prebuilt animations", "Intro loops"],
    notBestFor: ["Generated simulations", "Graphs"],
    demoStatus: "future-upgrade",
    demoMode: "placeholder",
    installed: false,
    installStatus: "missing",
    dependencyName: "lottie-react",
    primaryUseCase: { label: "Authored explainer", description: "Would play a prepared transformation animation." },
    fallbackTech: ["svg-motion", "css-animation"],
    performanceLevel: "medium",
    interactionLevel: "low",
    learningValue: "Good for polished repeated assets, not core reasoning.",
    recommendedForSciLoop: "evaluate-later",
    notes: "Use only when authored animation improves reuse.",
    comparison: { clarity: 7, performance: 7, interaction: 3, complexity: 5, dependencyCost: 5, bestVisualPattern: "Input -> Process -> Output", bestSciLoopUseCase: "Reusable explainer clips" },
    capabilityScores: scores({ Flows: "possible", "Concept cards": "possible" }),
    routerConceptHint: "prebuilt animation lottie",
  },
  {
    id: "rive",
    engineId: "rive",
    name: "Rive",
    description: "Future use for interactive character and icon animations.",
    bestFor: ["Interactive icons", "State machines", "Character feedback"],
    notBestFor: ["Data graphs", "Large simulations"],
    demoStatus: "future-upgrade",
    demoMode: "placeholder",
    installed: false,
    installStatus: "missing",
    dependencyName: "@rive-app/react-canvas",
    primaryUseCase: { label: "Interactive guide", description: "Would react to user understanding states." },
    fallbackTech: ["css-animation", "svg"],
    performanceLevel: "medium",
    interactionLevel: "high",
    learningValue: "Useful for interface emotion, not the base engine.",
    recommendedForSciLoop: "evaluate-later",
    notes: "Add after controlled recipe rendering is mature.",
    comparison: { clarity: 6, performance: 7, interaction: 8, complexity: 6, dependencyCost: 6, bestVisualPattern: "Feedback Loop", bestSciLoopUseCase: "Interactive affordances" },
    capabilityScores: scores({ "Concept cards": "possible", Flows: "possible" }),
    routerConceptHint: "interactive animation icon character",
  },
  {
    id: "pixijs",
    engineId: "pixijs",
    name: "PixiJS",
    description: "Future use for many animated 2D particles and sprites.",
    bestFor: ["Many 2D objects", "Particles", "Sprite fields"],
    notBestFor: ["Text dashboards", "Maps"],
    demoStatus: "heavy-dependency",
    demoMode: "placeholder",
    installed: false,
    installStatus: "missing",
    dependencyName: "pixi.js",
    primaryUseCase: { label: "Particle field", description: "Would show thousands of raw fragments organizing." },
    fallbackTech: ["canvas-2d", "svg-motion"],
    performanceLevel: "high",
    interactionLevel: "medium",
    learningValue: "Good upgrade when Canvas particle count becomes limiting.",
    recommendedForSciLoop: "evaluate-later",
    notes: "Canvas is enough for this command.",
    comparison: { clarity: 7, performance: 9, interaction: 7, complexity: 8, dependencyCost: 8, bestVisualPattern: "Random -> Organized", bestSciLoopUseCase: "Large 2D particle systems" },
    capabilityScores: scores({ Particles: "excellent", "Game labs": "possible" }),
    routerConceptHint: "many animated particles sprites",
  },
  {
    id: "phaser",
    engineId: "phaser",
    name: "Phaser",
    description: "Future use for game-like learning labs, scoring, missions, and levels.",
    bestFor: ["Game labs", "Missions", "Scoring"],
    notBestFor: ["Static explanations", "Dashboards"],
    demoStatus: "heavy-dependency",
    demoMode: "placeholder",
    installed: false,
    installStatus: "missing",
    dependencyName: "phaser",
    primaryUseCase: { label: "Learning mission", description: "Would turn understanding into tasks and levels." },
    fallbackTech: ["react-tailwind", "svg-motion"],
    performanceLevel: "high",
    interactionLevel: "high",
    learningValue: "Strong only when the goal is a learning game.",
    recommendedForSciLoop: "evaluate-later",
    notes: "Do not use for ordinary concept explanations.",
    comparison: { clarity: 6, performance: 8, interaction: 10, complexity: 9, dependencyCost: 9, bestVisualPattern: "Decision Tree", bestSciLoopUseCase: "Interactive labs" },
    capabilityScores: scores({ "Game labs": "excellent", Particles: "good" }),
    routerConceptHint: "game mission score level learning lab",
  },
  {
    id: "three",
    engineId: "three-r3f",
    name: "Three.js",
    description: "Future use for cosmic worlds, molecule worlds, and 3D fields.",
    bestFor: ["3D worlds", "Spatial concepts", "Fields"],
    notBestFor: ["Simple diagrams", "Dense text"],
    demoStatus: "heavy-dependency",
    demoMode: "placeholder",
    installed: true,
    installStatus: "installed",
    dependencyName: "three",
    primaryUseCase: { label: "Layered 3D reality", description: "Would show raw reality, hidden layers, and understanding in depth." },
    fallbackTech: ["svg-motion", "canvas-2d"],
    performanceLevel: "high",
    interactionLevel: "high",
    learningValue: "Use only when spatial depth teaches something essential.",
    recommendedForSciLoop: "evaluate-later",
    notes: "Installed, but intentionally kept as placeholder in this lab phase.",
    comparison: { clarity: 7, performance: 6, interaction: 8, complexity: 9, dependencyCost: 8, bestVisualPattern: "Field Influence", bestSciLoopUseCase: "Spatial simulations" },
    capabilityScores: scores({ "3D worlds": "excellent", Particles: "good", "GPU experiments": "possible" }),
    routerConceptHint: "3d spatial cosmic molecule field",
  },
  {
    id: "react-three-fiber",
    engineId: "three-r3f",
    name: "React Three Fiber",
    description: "React binding for Three.js spatial scenes.",
    bestFor: ["React 3D scenes", "Interactive spatial concepts"],
    notBestFor: ["Simple cards", "Charts"],
    demoStatus: "heavy-dependency",
    demoMode: "placeholder",
    installed: true,
    installStatus: "installed",
    dependencyName: "@react-three/fiber",
    primaryUseCase: { label: "React 3D frontier", description: "Would compose 3D understanding scenes in React." },
    fallbackTech: ["svg-motion", "canvas-2d"],
    performanceLevel: "high",
    interactionLevel: "high",
    learningValue: "Useful when 3D belongs inside the Visual OS component tree.",
    recommendedForSciLoop: "evaluate-later",
    notes: "Installed but not used as a live demo yet to keep Command 7 light.",
    comparison: { clarity: 7, performance: 6, interaction: 8, complexity: 9, dependencyCost: 8, bestVisualPattern: "Micro -> Macro", bestSciLoopUseCase: "3D concept worlds" },
    capabilityScores: scores({ "3D worlds": "excellent", Particles: "good" }),
    routerConceptHint: "react three fiber 3d spatial",
  },
  {
    id: "webgl",
    engineId: "webgl",
    name: "WebGL",
    description: "Native GPU-accelerated browser graphics.",
    bestFor: ["GPU graphics", "Shader visuals", "High object counts"],
    notBestFor: ["UI cards", "Plain diagrams"],
    demoStatus: "future-upgrade",
    demoMode: "placeholder",
    installed: true,
    installStatus: "native",
    primaryUseCase: { label: "GPU graphics", description: "Would accelerate dense visual experiments." },
    fallbackTech: ["canvas-2d", "svg-motion"],
    performanceLevel: "frontier",
    interactionLevel: "medium",
    learningValue: "Important fallback below WebGPU, but not first-line UI.",
    recommendedForSciLoop: "evaluate-later",
    notes: "Use through a controlled renderer, not raw one-off demos.",
    comparison: { clarity: 5, performance: 9, interaction: 7, complexity: 9, dependencyCost: 5, bestVisualPattern: "Field Influence", bestSciLoopUseCase: "GPU-backed visuals" },
    capabilityScores: scores({ Particles: "good", "3D worlds": "good", "GPU experiments": "good" }),
    routerConceptHint: "webgl gpu shader particles",
  },
  {
    id: "webgpu-experimental",
    engineId: "webgpu-experimental",
    name: "WebGPU Experimental",
    description: "Future frontier experiments with massive particles and compute-style visuals.",
    bestFor: ["Massive particles", "Compute visuals", "Frontier labs"],
    notBestFor: ["Production-only paths", "No-fallback experiences"],
    demoStatus: "experimental",
    demoMode: "placeholder",
    installed: false,
    installStatus: "experimental",
    primaryUseCase: { label: "Particle frontier", description: "Would test massive visual computation with required fallback." },
    fallbackTech: ["webgl", "canvas-2d", "svg-motion"],
    performanceLevel: "frontier",
    interactionLevel: "high",
    learningValue: "High future ceiling, but only after fallback discipline exists.",
    recommendedForSciLoop: "frontier-only",
    notes: "Every WebGPU route must have fallback.",
    comparison: { clarity: 5, performance: 10, interaction: 8, complexity: 10, dependencyCost: 8, bestVisualPattern: "Energy Flow", bestSciLoopUseCase: "Frontier particle labs" },
    capabilityScores: scores({ Particles: "excellent", "GPU experiments": "excellent" }),
    routerConceptHint: "webgpu gpu frontier massive particles compute",
  },
  {
    id: "maplibre",
    engineId: "maplibre",
    name: "MapLibre",
    description: "Future use for global problem solving maps and geographic context.",
    bestFor: ["Maps", "Geography", "Local/global impact"],
    notBestFor: ["Non-spatial concepts"],
    demoStatus: "future-upgrade",
    demoMode: "placeholder",
    installed: false,
    installStatus: "missing",
    dependencyName: "maplibre-gl",
    primaryUseCase: { label: "Global insight map", description: "Would show local raw information becoming global map understanding." },
    fallbackTech: ["react-tailwind", "svg-motion"],
    performanceLevel: "high",
    interactionLevel: "high",
    learningValue: "Useful when place and scale are essential.",
    recommendedForSciLoop: "evaluate-later",
    notes: "No map dependency added yet.",
    comparison: { clarity: 8, performance: 7, interaction: 8, complexity: 8, dependencyCost: 8, bestVisualPattern: "Local Action -> Global Impact", bestSciLoopUseCase: "Problem maps" },
    capabilityScores: scores({ Maps: "excellent", Flows: "possible" }),
    routerConceptHint: "map geography global problem local action location",
  },
  {
    id: "deckgl",
    engineId: "deckgl",
    name: "deck.gl",
    description: "Future use for large geospatial data layers and movement flows.",
    bestFor: ["Large geospatial data", "Movement flows", "Global layers"],
    notBestFor: ["Small maps", "Simple concept diagrams"],
    demoStatus: "heavy-dependency",
    demoMode: "placeholder",
    installed: false,
    installStatus: "missing",
    dependencyName: "deck.gl",
    primaryUseCase: { label: "Global data layers", description: "Would compare layered global data at scale." },
    fallbackTech: ["maplibre", "react-tailwind", "svg-motion"],
    performanceLevel: "frontier",
    interactionLevel: "high",
    learningValue: "Powerful only once SciLoop has large real geospatial data.",
    recommendedForSciLoop: "evaluate-later",
    notes: "Too heavy for this phase.",
    comparison: { clarity: 7, performance: 9, interaction: 8, complexity: 10, dependencyCost: 10, bestVisualPattern: "Network Growth", bestSciLoopUseCase: "Global-scale data overlays" },
    capabilityScores: scores({ Maps: "excellent", "GPU experiments": "good", Flows: "good" }),
    routerConceptHint: "deckgl geospatial large map movement flows data layers",
  },
];
