"use client";

import { useEffect, useState } from "react";
import type { EvolutionSnapshot } from "@/lib/evolution-engine";

const example = JSON.stringify({ discovery: "NASA discovers a hidden ocean beneath an icy moon", knowledgeGraph: { domains: ["Physics", "Astronomy"], nodeCount: 11, branchScore: 87 }, story: { angle: "The hidden problem", hook: "What if the ocean is hiding under the ice?", durationSeconds: 42 }, creative: { visualStyle: "Fast documentary", narrationStyle: "Documentary", musicStyle: "Cinematic", subtitleStyle: "Keyword highlight", thumbnail: "High-contrast planet reveal", caption: "A hidden ocean changes the question.", targetAudience: "Curious general audience" }, predicted: { views: 100000, reach: 80000, watchTimeSeconds: 36, retention3s: 92, averageRetention: 86, completionRate: 91, shares: 2200, saves: 1800, comments: 900, likes: 12000, profileVisits: 1200, followersGained: 400 }, actual: { views: 0, reach: 0, watchTimeSeconds: 0, retention3s: 0, averageRetention: 0, completionRate: 0, shares: 0, saves: 0, comments: 0, likes: 0, profileVisits: 0, followersGained: 0 } }, null, 2);

function Metric({ label, value, suffix = "" }: { label: string; value: number; suffix?: string }) { return <div className="rounded-2xl border border-white/8 bg-white/[.025] p-4"><div className="eyebrow">{label}</div><div className="mt-2 font-display text-3xl font-semibold text-white">{value}{suffix}</div></div>; }

export function EvolutionDashboard() {
  const [snapshot, setSnapshot] = useState<EvolutionSnapshot | null>(null);
  const [payload, setPayload] = useState(example);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  async function refresh() { const response = await fetch("/api/evolution"); const data = (await response.json()) as { evolution?: EvolutionSnapshot }; if (data.evolution) setSnapshot(data.evolution); }
  useEffect(() => { void refresh(); }, []);
  async function importExperiment() { setBusy(true); setMessage(""); try { const response = await fetch("/api/evolution", { method: "POST", headers: { "Content-Type": "application/json" }, body: payload }); const data = (await response.json()) as { evolution?: EvolutionSnapshot; error?: string }; if (data.evolution) { setSnapshot(data.evolution); setMessage("Experiment stored and learning state updated."); } else setMessage(data.error ?? "Import failed."); } catch { setMessage("Use valid experiment JSON."); } finally { setBusy(false); } }
  const metrics = snapshot?.metrics;
  return <div className="page-shell mx-auto max-w-[1500px] px-4 pb-24 pt-8 md:px-8 md:pt-12"><section className="relative overflow-hidden rounded-[36px] border border-white/10 bg-[#081522]/90 p-6 shadow-[0_30px_100px_rgba(0,0,0,.32)] md:p-10"><div className="absolute -right-24 -top-24 h-96 w-96 rounded-full bg-emerald-400/10 blur-3xl" /><div className="relative grid gap-8 lg:grid-cols-[1fr_.7fr] lg:items-end"><div><div className="eyebrow">SciLoop / Evolution Engine</div><h1 className="mt-5 max-w-4xl font-display text-5xl font-semibold leading-[.98] tracking-[-.06em] text-white md:text-7xl">Every reel teaches the <span className="text-gradient">next one.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-slate-300 md:text-lg">Prediction is only an advantage if reality can correct it. Import published analytics, measure the error, and promote only statistically supported patterns into the production memory.</p></div><div className="rounded-[26px] border border-emerald-200/15 bg-black/20 p-5"><div className="eyebrow">Import real analytics</div><textarea value={payload} onChange={(event) => setPayload(event.target.value)} rows={8} className="mt-4 w-full resize-y rounded-2xl border border-white/10 bg-white/[.04] p-4 font-mono text-[10px] leading-5 text-white outline-none focus:border-emerald-200/50" /><button onClick={importExperiment} disabled={busy} className="mt-4 w-full rounded-xl bg-emerald-200 px-5 py-3 text-xs font-semibold text-slate-950 transition hover:bg-white disabled:opacity-60">{busy ? "Learning…" : "Store experiment"}</button>{message && <div className="mt-3 text-xs text-emerald-200">{message}</div>}</div></div></section>

    <section className="mt-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="eyebrow">Platform evolution</div><h2 className="mt-2 font-display text-2xl font-semibold text-white">What the system knows now.</h2></div><span className="font-mono text-[10px] uppercase tracking-[.16em] text-slate-500">persistent local memory</span></div><div className="mt-5 grid gap-3 grid-cols-2 md:grid-cols-4 xl:grid-cols-8"><Metric label="Experiments" value={metrics?.experiments ?? 0} /><Metric label="Prediction accuracy" value={metrics?.predictionAccuracy ?? 0} suffix="%" /><Metric label="Avg completion" value={metrics?.averageCompletionRate ?? 0} suffix="%" /><Metric label="Avg shares" value={metrics?.averageShareRate ?? 0} /><Metric label="Avg saves" value={metrics?.averageSaveRate ?? 0} /><Metric label="Improvement" value={metrics?.improvementRate ?? 0} suffix="%" /><Metric label="Rules" value={metrics?.knowledgeBaseSize ?? 0} /><Metric label="Quality trend" value={metrics?.productionQualityTrend ?? 0} /></div></section>

    <div className="mt-8 grid gap-5 xl:grid-cols-[1fr_370px]"><section className="rounded-[30px] border border-white/10 bg-[#091321]/90 p-5 md:p-7"><div className="eyebrow">Performance history</div><h2 className="mt-2 font-display text-2xl font-semibold text-white">Prediction versus reality.</h2>{snapshot?.recent.length ? <div className="mt-6 space-y-4">{snapshot.recent.map((experiment) => <div key={experiment.id} className="grid gap-3 rounded-2xl border border-white/8 bg-white/[.025] p-4 md:grid-cols-[1fr_150px]"><div><div className="text-sm font-medium text-white">{experiment.discovery}</div><div className="mt-1 text-xs text-slate-500">{experiment.creative.visualStyle} · {experiment.story.durationSeconds}s · {experiment.analysis?.type ?? "prediction only"}</div></div><div className="flex items-end gap-1"><div className="h-10 flex-1 rounded-t bg-cyan-200/25" style={{ height: `${Math.min(100, experiment.predicted.completionRate)}%` }} /><div className="h-10 flex-1 rounded-t bg-emerald-200/55" style={{ height: `${Math.min(100, experiment.actual?.completionRate ?? 0)}%` }} /></div></div>)}<div className="mt-4 flex gap-4 text-[10px] text-slate-500"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-cyan-200/60" />Predicted</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-emerald-200" />Actual</span></div></div> : <div className="mt-8 rounded-2xl border border-dashed border-white/12 p-8 text-center text-sm leading-6 text-slate-500">No published experiments yet. Import the first real analytics record above to start the learning loop.</div>}</section><aside className="space-y-5"><section className="rounded-[26px] border border-white/10 bg-[#091321]/90 p-5"><div className="eyebrow">Learning rules</div><div className="mt-4 space-y-3">{snapshot?.rules.length ? snapshot.rules.map((rule) => <div key={rule.id} className="rounded-xl border border-emerald-200/15 bg-emerald-200/[.04] p-3"><div className="text-xs font-medium text-emerald-100">{rule.rule}</div><div className="mt-2 text-[10px] text-slate-500">{rule.evidence} · confidence {rule.confidence}%</div></div>) : <p className="text-sm leading-6 text-slate-500">Rules appear after at least 3 completed experiments show a measurable lift.</p>}</div></section><section className="rounded-[26px] border border-amber-200/15 bg-amber-200/[.04] p-5"><div className="eyebrow">Next improvement</div><div className="mt-3 space-y-2 text-sm leading-6 text-amber-100/80">{(snapshot?.suggestions ?? ["Import real analytics to calibrate the simulator."]).map((suggestion) => <p key={suggestion}>→ {suggestion}</p>)}</div></section></aside></div>

    <section className="mt-8 grid gap-5 lg:grid-cols-2"><div className="rounded-[30px] border border-rose-200/15 bg-rose-200/[.035] p-5 md:p-7"><div className="eyebrow">Failure analysis</div><h2 className="mt-2 font-display text-2xl font-semibold text-white">Assumptions to retire.</h2><div className="mt-5 space-y-3">{snapshot?.failures.length ? snapshot.failures.map((item) => <div key={item.id} className="rounded-xl border border-rose-200/10 p-3 text-xs leading-5 text-rose-100/80">{item.analysis?.rootCauses.join(" · ")}</div>) : <p className="text-sm leading-6 text-slate-500">No failures recorded yet.</p>}</div></div><div className="rounded-[30px] border border-cyan-200/15 bg-cyan-200/[.035] p-5 md:p-7"><div className="eyebrow">Success analysis</div><h2 className="mt-2 font-display text-2xl font-semibold text-white">Patterns worth reusing.</h2><div className="mt-5 space-y-3">{snapshot?.successes.length ? snapshot.successes.map((item) => <div key={item.id} className="rounded-xl border border-cyan-200/10 p-3 text-xs leading-5 text-cyan-100/80">{item.analysis?.strengths.join(" · ")}</div>) : <p className="text-sm leading-6 text-slate-500">No successes recorded yet.</p>}</div></div></section>
  </div>;
}
