import type { VisualFeedback } from "./feedback.types";

export const feedbackExamples: VisualFeedback[] = [
  {
    id: "feedback-example-fourier",
    recipeId: "recipe-fourier-transform",
    patternId: "signal-decomposition",
    engineId: "svg-motion",
    concept: "Fourier Transform",
    visualType: "signal-decomposition",
    rating: "clear",
    clarityScore: 4,
    complexityScore: 3,
    motionScore: 4,
    usefulnessScore: 4,
    selectedIssues: ["missing-math-layer"],
    selectedImprovements: ["add-math-layer"],
    freeText: "The intuition is clear; now show the equation as an optional layer.",
    audienceLevel: "student",
    createdAt: "2026-06-20T09:00:00.000Z",
    source: "manual",
  },
  {
    id: "feedback-example-energy",
    recipeId: "recipe-heat-to-organized-energy",
    patternId: "energy-flow",
    engineId: "canvas-2d",
    concept: "Heat to Organized Energy",
    visualType: "flow-system",
    rating: "okay",
    clarityScore: 3,
    complexityScore: 3,
    motionScore: 2,
    usefulnessScore: 4,
    selectedIssues: ["not-enough-motion"],
    selectedImprovements: ["add-step-by-step-motion"],
    freeText: "Make the change from random motion to directed flow more visible.",
    audienceLevel: "student",
    createdAt: "2026-06-20T09:05:00.000Z",
    source: "manual",
  },
  {
    id: "feedback-example-gravity",
    recipeId: "recipe-gravity-field",
    patternId: "field-influence",
    engineId: "three-r3f",
    concept: "Gravity",
    visualType: "field-influence",
    rating: "clear",
    clarityScore: 4,
    complexityScore: 3,
    motionScore: 3,
    usefulnessScore: 4,
    selectedIssues: ["not-interactive-enough"],
    selectedImprovements: ["add-interaction"],
    freeText: "Let me move a mass and see how the field changes.",
    audienceLevel: "general",
    createdAt: "2026-06-20T09:10:00.000Z",
    source: "manual",
  },
  {
    id: "feedback-example-global-solving",
    recipeId: "recipe-global-problem-solving",
    patternId: "local-action-global-impact",
    engineId: "maplibre",
    concept: "Global Problem Solving",
    visualType: "network",
    rating: "okay",
    clarityScore: 3,
    complexityScore: 3,
    motionScore: 3,
    usefulnessScore: 4,
    selectedIssues: ["unclear-layers"],
    selectedImprovements: ["show-hidden-mechanism"],
    freeText: "A map layer would make the local-to-global relationship concrete.",
    audienceLevel: "general",
    createdAt: "2026-06-20T09:15:00.000Z",
    source: "manual",
  },
  {
    id: "feedback-example-understanding",
    recipeId: "recipe-random-information-human-understanding",
    patternId: "random-to-organized",
    engineId: "svg-motion",
    concept: "Random Information to Understanding",
    visualType: "transformation",
    rating: "confusing",
    clarityScore: 2,
    complexityScore: 4,
    motionScore: 3,
    usefulnessScore: 3,
    selectedIssues: ["missing-real-life-example", "unclear-flow"],
    selectedImprovements: ["add-real-life-example"],
    freeText: "It feels abstract. Show how a student turns messy notes into an explanation.",
    audienceLevel: "student",
    createdAt: "2026-06-20T09:20:00.000Z",
    source: "manual",
  },
];
